"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test");const root=path.resolve(__dirname,"..");const read=file=>fs.readFileSync(path.join(root,file),"utf8");
test("release evidence is commit-bound, hashed, tenant-isolated, and public only as metadata",()=>{const migration=read("migrations/20260721_goodbase_operational_proof.sql"),helper=read("scripts/lib/goodbase-evidence.js"),routes=read("src/routes/goodbase-experience.routes.js");assert.match(migration,/goodbase_release_evidence/);assert.match(migration,/release_commit TEXT NOT NULL CHECK/);assert.match(migration,/FORCE ROW LEVEL SECURITY/);assert.match(helper,/createHash\("sha256"\)/);assert.match(helper,/renameSync/);assert.match(routes,/evidence\/releases\/\:commit/);assert.doesNotMatch(routes,/report_json.*evidence\/releases/);});
test("certification measures all twelve operational requirements and stores its report",()=>{const source=read("scripts/goodbase-certify.js");for(let number=1;number<=12;number+=1)assert.match(source,new RegExp(`phase\\(${number},`));assert.match(source,/preserveEvidence/);assert.match(source,/non-production-chaos-evidence/);assert.match(source,/commercial-provider-families/);assert.match(source,/jsonb_array_length\(artifacts_json\)/);assert.doesNotMatch(source,/cardinality\(artifacts_json\)/);});
test("controller registry supports every required production controller family",()=>{const migration=read("migrations/20260721_goodbase_operational_proof.sql"),routes=read("src/routes/goodbase-production.routes.js");for(const family of ["infrastructure","recovery","hosting","domain","preview","regional","cdn","distribution","embedding","import"]){assert.match(migration,new RegExp(`'${family}'`));assert.match(routes,new RegExp(`"${family}"`));}});
test("controller operations require signed callbacks with rollback or failure evidence",()=>{const route=read("src/routes/goodbase-controller-callback.routes.js"),service=read("src/services/goodbase-production.service.js"),migration=read("migrations/20260721_goodbase_operational_proof.sql");assert.match(route,/X-Goodbase-Timestamp/);assert.match(route,/timingSafeEqual/);assert.match(route,/rollbackEvidence/);assert.match(route,/failure_json/);assert.match(service,/awaiting_callback/);assert.match(service,/must prove completion or accept a signed callback/);assert.match(migration,/callback_received_at/);});
test("required CI publishes tests, security status, SBOM, provenance, scans, and retained evidence",()=>{const ci=read(".github/workflows/ci.yml"),assurance=read(".github/workflows/goodbase-assurance.yml");for(const value of ["pull_request","security:gate","npm audit","npm sbom","upload-artifact","retention-days: 90"])assert.match(ci,new RegExp(value));for(const value of ["attestations: write","attest-build-provenance","workflow_dispatch","aquasecurity/trivy-action@v0.36.0","retention-days: 90"])assert.match(assurance,new RegExp(value));});
test("CI evidence is recorded only after exact-commit backend, assurance, and SDK runs with retained artifacts",()=>{const source=read("scripts/goodbase-record-ci.js");assert.match(source,/head_sha/);assert.match(source,/conclusion !== "success"/);assert.match(source,/artifact\.expired/);assert.match(source,/goodbase-required-ci-/);assert.match(source,/goodbase-release-evidence/);assert.match(source,/GOODBASE_SDK_CONFORMANCE_RUN_ID/);assert.match(source,/goodbase-sdk-conformance-/);assert.match(source,/preserveEvidence/);});

test("SDK conformance retains exact-commit packages and checksums from every supported platform",()=>{const source=read(".github/workflows/goodbase-sdk-conformance.yml");for(const platform of ["js-python","swift","android","flutter","dotnet"])assert.match(source,new RegExp(`goodbase-sdk-${platform}-`));assert.match(source,/SHA256SUMS/);assert.match(source,/RELEASE_COMMIT/);assert.match(source,/retention-days: 90/);assert.match(source,/needs: \[javascript-python, swift, android, flutter, dotnet\]/);});
