"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");

test("official SDK manifest names package sources and keeps device certification pending",()=>{const manifest=JSON.parse(read("sdks/manifest.json"));assert.equal(manifest.official.javascript,"sdks/javascript/index.js");assert.equal(manifest.certification.status,"pending-real-devices");assert.equal(manifest.certification.required.length,5);for(const value of Object.values(manifest.packages))assert.equal(value.status,"source-ready");});
test("native SDKs contain automatic crash, lifecycle, consent, and offline paths",()=>{const sources=["sdks/swift/Sources/Goodbase/GoodbaseTelemetry.swift","sdks/kotlin/src/main/kotlin/app/goodos/goodbase/GoodbaseTelemetry.kt","sdks/dart/lib/goodbase_telemetry.dart","sdks/csharp/Goodbase/GoodbaseTelemetry.cs","sdks/python/goodbase/telemetry.py","sdks/javascript/telemetry.js"].map(read).join("\n");for(const term of ["consent","session","crash","trace","breadcrumb","flush"])assert.match(sources,new RegExp(term,"i"));assert.match(read("sdks/kotlin/src/main/cpp/goodbase_crash_handler.cpp"),/SIGABRT/);});
test("native SDK sources compile without ambiguous framework overloads",()=>{assert.match(read("sdks/kotlin/src/main/cpp/goodbase_crash_handler.cpp"),/#include <initializer_list>/);assert.match(read("sdks/kotlin/build.gradle.kts"),/sourceCompatibility = JavaVersion[.]VERSION_17/);assert.match(read("sdks/kotlin/build.gradle.kts"),/jvmToolchain\(17\)/);assert.match(read("sdks/csharp/Goodbase/GoodbaseTelemetry.cs"),/Select\(value => JsonSerializer[.]Serialize\(value\)\)/);});
test(".NET SDK emits deterministic NuGet and portable symbol packages",()=>{const project=read("sdks/csharp/Goodbase/Goodbase.csproj");assert.match(project,/<Deterministic>true<\/Deterministic>/);assert.match(project,/<IncludeSymbols>true<\/IncludeSymbols>/);assert.match(project,/<SymbolPackageFormat>snupkg<\/SymbolPackageFormat>/);});
test("JavaScript client sends attestation and telemetry contracts",async()=>{const calls=[];const response={ok:true,status:200,headers:{get(){return null;}},async text(){return '{"success":true}';}};const {GoodbaseClient}=require("../sdks/javascript");const client=new GoodbaseClient({accessToken:"access",attestationToken:"attest",fetch:async(url,options)=>{calls.push({url,options});return response;}});await client.captureCrash("app",{title:"controlled"});assert.match(calls[0].url,/telemetry\/crashes$/);assert.equal(calls[0].options.headers.Authorization,"Bearer access");assert.equal(calls[0].options.headers["X-Goodbase-Attestation"],"attest");assert.equal(JSON.parse(calls[0].options.body).appId,"app");});
