"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test");
const root=path.resolve(__dirname,"..");const read=(file)=>fs.readFileSync(path.join(root,file),"utf8");

test("audit correction migration adds governed IaC, extensions, and AI with forced tenant isolation",()=>{const sql=read("migrations/20260721_goodbase_audit_corrections.sql");for(const table of ["goodbase_iac_stacks","goodbase_iac_locks","goodbase_iac_runs","goodbase_extension_publishers","goodbase_extension_packages","goodbase_extension_versions","goodbase_extension_installations","goodbase_ai_providers","goodbase_ai_models","goodbase_ai_policies","goodbase_ai_prompt_templates","goodbase_ai_runs","goodbase_ai_evaluation_runs"])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/goodbase_backend_service/);assert.doesNotMatch(sql,/status TEXT NOT NULL DEFAULT 'ready'/);});
test("IaC requires secret-backed state, locks, exact commits, idempotency, rollback, MFA, and a recent verified controller",()=>{const routes=read("src/routes/goodbase-ecosystem.routes.js");assert.ok(routes.includes("secret://"));for(const value of ["goodbase_iac_locks","Idempotency-Key","exact source commit","verified rollback reference","last_health_at>NOW\\(\\)-INTERVAL '10 minutes'","GOODBASE_PRIVILEGED_MFA_REQUIRED","GOODBASE_IAC_CONTROLLER_UNAVAILABLE"])assert.match(routes,new RegExp(value));});
test("extension publication is signed, SBOM-backed, permission bounded, controller reviewed, and rollback capable",()=>{const routes=read("src/routes/goodbase-ecosystem.routes.js"),sql=read("migrations/20260721_goodbase_audit_corrections.sql");for(const value of ["signature","sbomRef","permissionManifest","extension.review","controllerOperationId","rollback_manifest_json","secret_refs"])assert.match(routes+sql,new RegExp(value,"i"));assert.match(routes,/result_json->>'approved'='true'/);});
test("AI gateway verifies live providers and enforces attestation, policy, quotas, tools, safety, structured output, idempotency, and metering",()=>{const service=read("src/services/goodbase-ai.service.js"),routes=read("src/routes/goodbase-ecosystem.routes.js");for(const value of ["validateAttestationToken","GOODBASE_AI_QUOTA_EXCEEDED","allowed_tools","blockedTerms","json_schema","Idempotency-Key","cost_microunits","provider.status='ready'","GOODBASE_AI_SECRET_MISSING"])assert.match(service+routes,new RegExp(value));assert.doesNotMatch(routes,/process\.env\[request/);});
test("native offline stores persist encrypted per-user queues and delete them on logout",()=>{const swift=read("sdks/swift/Sources/Goodbase/GoodbaseOfflineStore.swift"),kotlin=read("sdks/kotlin/src/main/kotlin/app/goodos/goodbase/GoodbaseOfflineStore.kt"),dart=read("sdks/dart/lib/goodbase_offline.dart");assert.match(swift,/AES\.GCM/);assert.match(swift,/completeUntilFirstUserAuthentication/);assert.match(kotlin,/GoodbaseOfflineCipher/);assert.match(kotlin,/ATOMIC_MOVE/);assert.match(dart,/GoodbaseOfflineCipher/);for(const source of [swift,kotlin,dart]){assert.match(source,/idempotency/i);assert.match(source,/clearForLogout/);}});
test("SDK activation requires exact-commit CI, signed artifacts, SBOM, compatibility data, and complete conformance",()=>{const routes=read("src/routes/goodbase-production.routes.js"),cert=read("scripts/goodbase-certify.js");for(const value of ["signature_ref","sbom_ref","changelog_ref","compatibility_matrix_json","goodbase_release_evidence","rest","graphql","realtime","offline","storage","auth","attestation","product"])assert.match(routes+cert,new RegExp(value));assert.match(cert,/client_platform=ANY\(ARRAY\['swift','kotlin','flutter'\]\)/);});
test("certification requires all named controller families with fresh capability and version evidence",()=>{const source=read("scripts/goodbase-certify.js");for(const family of ["infrastructure","recovery","hosting","domain","preview","regional","cdn","distribution","embedding","import"])assert.match(source,new RegExp(`"${family}"`));assert.match(source,/last_health_at>NOW\(\)-INTERVAL '10 minutes'/);assert.match(source,/last_health_json->>'version'/);assert.match(source,/jsonb_array_length\(last_health_json->'capabilities'\)/);});
