"use strict";

const crypto = require("crypto");
const bcrypt = require("bcryptjs");
const express = require("express");
const rateLimit = require("express-rate-limit");
const database = require("../config/database");
const env = require("../config/env");
const authRequired = require("../middleware/authRequired");
const tenantContext = require("../middleware/tenantContext");
const { dataPlaneAdminRequired } = require("./data-plane.routes");
const { issueSessionForUser } = require("../services/auth.service");
const { queueEmail } = require("../services/notification.service");
const { encryptValue, decryptValue } = require("../services/secret.service");
const {
  DEFAULT_SCOPE, sha256, runAssuranceSuite, exchangeAttestation,
  validateAttestationToken, verifyMessagingProvider, verifyConsumerAuthProvider
} = require("../services/goodbase-growth.service");

const publicRouter=express.Router();
const authenticatedRouter=express.Router();
const limiter=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:true,legacyHeaders:false,message:{success:false,code:"GOODBASE_GROWTH_RATE_LIMITED",message:"Too many requests. Try again later."}});

function clean(value,max=200){return String(value??"").trim().replace(/[\u0000-\u001f\u007f]/g," ").slice(0,max);}
function scope(request){return request.tenantContext?{organizationId:request.tenantContext.organizationId,projectId:request.tenantContext.projectId,environmentId:request.tenantContext.environmentId}:DEFAULT_SCOPE;}
function e164(value){const phone=String(value||"").replace(/[\s().-]/g,"");return /^\+[1-9]\d{7,14}$/.test(phone)?phone:null;}
function email(value){const normalized=String(value||"").trim().toLowerCase();return normalized.length<=320&&/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(normalized)?normalized:null;}
function timezone(value){const candidate=clean(value,80);if(!candidate)return null;try{new Intl.DateTimeFormat("en-US",{timeZone:candidate}).format();return candidate;}catch{return null;}}
function cookieOptions(){return{httpOnly:true,secure:env.authCookieSecure,sameSite:env.authCookieSameSite,domain:env.authCookieDomain,path:"/",maxAge:env.sessionDays*24*60*60*1000};}
function mfaRequired(request,response,next){if(!request.auth?.mfaVerified)return response.status(428).json({success:false,code:"GOODBASE_PRIVILEGED_MFA_REQUIRED",message:"Verify MFA before changing production trust or messaging configuration."});return next();}
async function enforcePublicAttestation(request,appId,platform="web"){const policy=await database.query(`SELECT mode FROM goodbase_attestation_policies WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND app_id=$4 AND platform=$5 LIMIT 1`,[DEFAULT_SCOPE.organizationId,DEFAULT_SCOPE.projectId,DEFAULT_SCOPE.environmentId,appId,platform]);if(policy.rows[0]?.mode!=="enforce")return null;const token=String(request.get("X-Goodbase-Attestation")||"");if(!token)throw Object.assign(new Error("A valid app attestation token is required."),{code:"ATTESTATION_REQUIRED",statusCode:401});return validateAttestationToken(token,{appId});}

publicRouter.get("/auth/providers",async(_request,response,next)=>{try{const result=await database.query(`SELECT id,provider_type,display_name,status,issuer_url,scopes FROM goodbase_consumer_auth_providers WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY display_name`,[DEFAULT_SCOPE.organizationId,DEFAULT_SCOPE.projectId,DEFAULT_SCOPE.environmentId]);return response.json({success:true,providers:result.rows.map(row=>({...row,available:row.status==="enabled"}))});}catch(error){return next(error);}});

publicRouter.post("/auth/anonymous",limiter,async(request,response,next)=>{try{
  await enforcePublicAttestation(request,clean(request.body?.appId,100)||"goodbase",clean(request.body?.platform,20)||"web");
  const provider=await database.query(`SELECT * FROM goodbase_consumer_auth_providers WHERE id='auth_consumer_anonymous' AND status='enabled'`);
  const policy=await database.query(`SELECT anonymous_users_enabled FROM goodbase_auth_security_policies WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3`,[DEFAULT_SCOPE.organizationId,DEFAULT_SCOPE.projectId,DEFAULT_SCOPE.environmentId]);
  if(!provider.rows[0]||policy.rows[0]?.anonymous_users_enabled!==true)return response.status(503).json({success:false,code:"ANONYMOUS_AUTH_DISABLED",message:"Anonymous accounts are not enabled for this application."});
  const client=await database.pool.connect();let user;
  try{await client.query("BEGIN");const marker=crypto.randomUUID();const created=await client.query(`INSERT INTO users(email,password_hash,display_name,platform_role,status,email_verified,auth_metadata_json) VALUES($1,NULL,'Guest','user','active',TRUE,$2::jsonb) RETURNING *`,[`anon+${marker}@anonymous.goodbase.invalid`,JSON.stringify({anonymous:true,anonymousId:marker,registrationSource:"goodbase_consumer_anonymous"})]);user=created.rows[0];await client.query(`INSERT INTO goodbase_auth_identities(organization_id,user_id,provider,provider_subject,verified,profile_json) VALUES($1,$2,'anonymous',$3,TRUE,'{"upgradeable":true}'::jsonb)`,[DEFAULT_SCOPE.organizationId,user.id,marker]);await client.query(`INSERT INTO app_memberships(user_id,app_id,role,status) SELECT $1,id,'member','active' FROM apps WHERE id=COALESCE(NULLIF($2,''),'goodbase') ON CONFLICT(user_id,app_id) DO NOTHING`,[user.id,clean(request.body?.appId,100)]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  const session=await issueSessionForUser({user,ipAddress:request.ip,userAgent:request.get("user-agent"),authMethod:"anonymous"});response.cookie(env.authCookieName,session.token,cookieOptions());return response.status(201).json({success:true,...session,upgradeRequired:true});
}catch(error){return next(error);}});

publicRouter.post("/auth/phone/start",limiter,async(request,response,next)=>{try{
  const phone=e164(request.body?.phone);if(!phone)return response.status(400).json({success:false,code:"PHONE_INVALID",message:"Enter a valid E.164 phone number."});await enforcePublicAttestation(request,clean(request.body?.appId,100)||"goodbase",clean(request.body?.platform,20)||"web");
  const provider=await database.query(`SELECT * FROM goodbase_consumer_auth_providers WHERE id='auth_consumer_phone' AND status='enabled' AND controller_url IS NOT NULL AND secret_ref IS NOT NULL`);
  if(!provider.rows[0])return response.status(503).json({success:false,code:"SMS_PROVIDER_UNAVAILABLE",message:"Phone authentication is not configured."});
  const identity=await database.query(`SELECT identity.user_id FROM goodbase_auth_identities identity JOIN users ON users.id=identity.user_id WHERE identity.phone_e164=$1 AND identity.verified=TRUE AND identity.unlinked_at IS NULL AND users.status='active' LIMIT 1`,[phone]);
  const generic={success:true,accepted:true,message:"If the phone is eligible, a one-time code will be sent."};if(!identity.rows[0])return response.status(202).json(generic);
  const code=String(crypto.randomInt(0,1000000)).padStart(6,"0");const challenge=await database.query(`INSERT INTO goodbase_auth_challenges(organization_id,project_id,environment_id,user_id,challenge_type,destination_hash,secret_hash,expires_at,metadata_json) VALUES($1,$2,$3,$4,'phone_otp',$5,$6,NOW()+INTERVAL '10 minutes','{"singleUse":true}'::jsonb) RETURNING id`,[DEFAULT_SCOPE.organizationId,DEFAULT_SCOPE.projectId,DEFAULT_SCOPE.environmentId,identity.rows[0].user_id,sha256(phone),sha256(code)]);
  await database.query(`INSERT INTO goodbase_sms_deliveries(organization_id,project_id,environment_id,user_id,destination_hash,encrypted_payload,provider_id,purpose,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,'phone_otp',NOW()+INTERVAL '10 minutes')`,[DEFAULT_SCOPE.organizationId,DEFAULT_SCOPE.projectId,DEFAULT_SCOPE.environmentId,identity.rows[0].user_id,sha256(phone),encryptValue(JSON.stringify({phone,code,challengeId:challenge.rows[0].id})),provider.rows[0].id]);return response.status(202).json(generic);
}catch(error){return next(error);}});

publicRouter.post("/auth/phone/verify",limiter,async(request,response,next)=>{try{
  const phone=e164(request.body?.phone);const code=clean(request.body?.code,12);if(!phone||!/^\d{6}$/.test(code))return response.status(401).json({success:false,code:"PHONE_OTP_INVALID",message:"The phone challenge is invalid or expired."});
  const client=await database.pool.connect();let userId;
  try{await client.query("BEGIN");const challenge=await client.query(`SELECT * FROM goodbase_auth_challenges WHERE challenge_type='phone_otp' AND destination_hash=$1 AND status='pending' AND expires_at>NOW() ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[sha256(phone)]);const row=challenge.rows[0];if(!row||row.secret_hash!==sha256(code)){if(row)await client.query(`UPDATE goodbase_auth_challenges SET attempts=attempts+1,status=CASE WHEN attempts+1>=max_attempts THEN 'locked' ELSE status END WHERE id=$1`,[row.id]);await client.query("COMMIT");return response.status(401).json({success:false,code:"PHONE_OTP_INVALID",message:"The phone challenge is invalid or expired."});}await client.query(`UPDATE goodbase_auth_challenges SET status='consumed',verified_at=NOW(),consumed_at=NOW(),attempts=attempts+1 WHERE id=$1`,[row.id]);await client.query("COMMIT");userId=row.user_id;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  const user=await database.query(`SELECT * FROM users WHERE id=$1`,[userId]);const session=await issueSessionForUser({user:user.rows[0],ipAddress:request.ip,userAgent:request.get("user-agent"),authMethod:"phone_otp"});response.cookie(env.authCookieName,session.token,cookieOptions());return response.json({success:true,...session});
}catch(error){return next(error);}});

publicRouter.post("/attestation/challenge",limiter,async(request,response,next)=>{try{
  const appId=clean(request.body?.appId,100);const platform=clean(request.body?.platform,20);const policy=await database.query(`SELECT * FROM goodbase_attestation_policies WHERE app_id=$1 AND platform=$2 AND mode<>'disabled' LIMIT 1`,[appId,platform]);if(!policy.rows[0])return response.status(404).json({success:false,code:"ATTESTATION_POLICY_UNAVAILABLE",message:"No attestation policy is configured for this application and platform."});
  const nonce=crypto.randomBytes(32).toString("base64url");const challenge=await database.query(`INSERT INTO goodbase_attestation_challenges(policy_id,nonce_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '5 minutes') RETURNING id,expires_at`,[policy.rows[0].id,sha256(nonce)]);return response.status(201).json({success:true,challengeId:challenge.rows[0].id,nonce,provider:policy.rows[0].provider,expiresAt:challenge.rows[0].expires_at});
}catch(error){return next(error);}});

publicRouter.post("/attestation/exchange",limiter,async(request,response,next)=>{const started=process.hrtime.bigint();let row=null;try{
  const challenge=await database.query(`SELECT challenge.id AS challenge_id,challenge.status AS challenge_status,challenge.expires_at AS challenge_expires_at,challenge.nonce_hash,policy.* FROM goodbase_attestation_challenges challenge JOIN goodbase_attestation_policies policy ON policy.id=challenge.policy_id WHERE challenge.id=$1 AND challenge.nonce_hash=$2 LIMIT 1`,[request.body?.challengeId,sha256(request.body?.nonce)]);if(!challenge.rows[0])return response.status(401).json({success:false,code:"ATTESTATION_CHALLENGE_INVALID",message:"Attestation challenge is invalid or expired."});row=challenge.rows[0];const challengeRecord={id:row.challenge_id,status:row.challenge_status,expires_at:row.challenge_expires_at};const result=await exchangeAttestation({policy:row,challenge:challengeRecord,assertion:request.body?.assertion||{}});await database.query(`INSERT INTO goodbase_attestation_events(organization_id,project_id,environment_id,app_id,policy_id,jti,outcome,reason_code,endpoint,latency_ms) VALUES($1,$2,$3,$4,$5,$6,'accepted','VERIFIED',$7,$8)`,[row.organization_id,row.project_id,row.environment_id,row.app_id,row.id,result.jti,request.originalUrl,Number(process.hrtime.bigint()-started)/1e6]);return response.json({success:true,attestationToken:result.token,expiresIn:result.expiresIn});
}catch(error){if(row)await database.query(`INSERT INTO goodbase_attestation_events(organization_id,project_id,environment_id,app_id,policy_id,outcome,reason_code,endpoint,latency_ms,detail_json) VALUES($1,$2,$3,$4,$5,'rejected',$6,$7,$8,$9::jsonb)`,[row.organization_id,row.project_id,row.environment_id,row.app_id,row.id,clean(error.code||"ATTESTATION_REJECTED",80),request.originalUrl,Number(process.hrtime.bigint()-started)/1e6,JSON.stringify({challengeId:row.challenge_id})]).catch(()=>{});return next(error);}});

authenticatedRouter.use(authRequired,tenantContext);

authenticatedRouter.post("/auth/anonymous/upgrade/start",limiter,async(request,response,next)=>{try{
  const proposed=email(request.body?.email);const password=String(request.body?.password||"");if(!proposed||password.length<12||password.length>128)return response.status(400).json({success:false,message:"A valid email and password between 12 and 128 characters are required."});const current=await database.query(`SELECT auth_metadata_json FROM users WHERE id=$1`,[request.user.id]);if(current.rows[0]?.auth_metadata_json?.anonymous!==true)return response.status(409).json({success:false,code:"ACCOUNT_NOT_ANONYMOUS",message:"This account is already permanent."});const existing=await database.query(`SELECT 1 FROM users WHERE LOWER(email)=LOWER($1) AND id<>$2`,[proposed,request.user.id]);if(existing.rows[0])return response.status(409).json({success:false,code:"EMAIL_IN_USE",message:"That email is already registered."});const code=String(crypto.randomInt(0,1000000)).padStart(6,"0");const encryptedPasswordHash=encryptValue(await bcrypt.hash(password,12));await database.query(`INSERT INTO goodbase_auth_challenges(organization_id,project_id,environment_id,user_id,challenge_type,destination_hash,secret_hash,expires_at,metadata_json) VALUES($1,$2,$3,$4,'account_upgrade',$5,$6,NOW()+INTERVAL '10 minutes',$7::jsonb)`,[scope(request).organizationId,scope(request).projectId,scope(request).environmentId,request.user.id,sha256(proposed),sha256(code),JSON.stringify({proposedEmail:proposed,encryptedPasswordHash})]);await queueEmail({templateKey:"auth.account_upgrade",toEmail:proposed,toName:request.user.displayName||"Goodbase user",subject:"Verify your Goodbase account",bodyText:`Your account-upgrade code is ${code}. It expires in 10 minutes.`,bodyHtml:`<p>Your account-upgrade code is <strong>${code}</strong>.</p><p>It expires in 10 minutes.</p>`,...scope(request)});return response.status(202).json({success:true,accepted:true});
}catch(error){return next(error);}});

authenticatedRouter.post("/auth/anonymous/upgrade/verify",limiter,async(request,response,next)=>{try{
  const proposed=email(request.body?.email);const code=clean(request.body?.code,12);if(!proposed||!/^[0-9]{6}$/.test(code))return response.status(401).json({success:false,code:"ACCOUNT_UPGRADE_INVALID",message:"The account upgrade challenge is invalid or expired."});const client=await database.pool.connect();try{await client.query("BEGIN");const result=await client.query(`SELECT * FROM goodbase_auth_challenges WHERE user_id=$1 AND challenge_type='account_upgrade' AND destination_hash=$2 AND status='pending' AND expires_at>NOW() ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[request.user.id,sha256(proposed)]);const row=result.rows[0];if(!row||row.secret_hash!==sha256(code)||!row.metadata_json?.encryptedPasswordHash){await client.query("ROLLBACK");return response.status(401).json({success:false,code:"ACCOUNT_UPGRADE_INVALID",message:"The account upgrade challenge is invalid or expired."});}const passwordHash=decryptValue(row.metadata_json.encryptedPasswordHash);await client.query(`UPDATE users SET email=$2,password_hash=$3,email_verified=TRUE,auth_metadata_json=COALESCE(auth_metadata_json,'{}'::jsonb)||'{"anonymous":false}'::jsonb,password_updated_at=NOW(),updated_at=NOW() WHERE id=$1`,[request.user.id,proposed,passwordHash]);await client.query(`UPDATE goodbase_auth_challenges SET status='consumed',verified_at=NOW(),consumed_at=NOW(),metadata_json=metadata_json-'encryptedPasswordHash' WHERE id=$1`,[row.id]);await client.query(`INSERT INTO goodbase_auth_identities(organization_id,user_id,provider,provider_subject,email_normalized,verified) VALUES($1,$2,'password',$3,$3,TRUE) ON CONFLICT(provider,provider_subject) DO UPDATE SET verified=TRUE,unlinked_at=NULL`,[scope(request).organizationId,request.user.id,proposed]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}return response.json({success:true,upgraded:true,email:proposed});
}catch(error){return next(error);}});

authenticatedRouter.get("/auth/identities",async(request,response,next)=>{try{const result=await database.query(`SELECT id,provider,email_normalized,phone_e164,verified,linked_at,unlinked_at FROM goodbase_auth_identities WHERE user_id=$1 ORDER BY linked_at`,[request.user.id]);return response.json({success:true,identities:result.rows});}catch(error){return next(error);}});

authenticatedRouter.delete("/auth/identities/:id",mfaRequired,async(request,response,next)=>{try{const client=await database.pool.connect();try{await client.query("BEGIN");const identity=await client.query(`SELECT * FROM goodbase_auth_identities WHERE id=$1 AND user_id=$2 AND unlinked_at IS NULL FOR UPDATE`,[request.params.id,request.user.id]);if(!identity.rows[0]){await client.query("ROLLBACK");return response.status(404).json({success:false,message:"Linked identity not found."});}const remaining=await client.query(`SELECT COUNT(*)::int AS count FROM goodbase_auth_identities WHERE user_id=$1 AND unlinked_at IS NULL AND id<>$2`,[request.user.id,request.params.id]);if(remaining.rows[0].count<1){await client.query("ROLLBACK");return response.status(409).json({success:false,code:"LAST_IDENTITY_REQUIRED",message:"Link another sign-in method before removing this identity."});}await client.query(`UPDATE goodbase_auth_identities SET unlinked_at=NOW(),verified=FALSE WHERE id=$1`,[request.params.id]);await client.query("COMMIT");return response.json({success:true,unlinked:true});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}catch(error){return next(error);}});

authenticatedRouter.post("/messaging/devices",limiter,async(request,response,next)=>{try{
  const tenant=scope(request);const appId=clean(request.body?.appId,100);const platform=clean(request.body?.platform,20);const rawToken=String(request.body?.deviceToken||"").trim();const deviceTimezone=request.body?.timezone?timezone(request.body.timezone):null;if(!appId||!["ios","android","flutter","web"].includes(platform)||!rawToken||rawToken.length>4096||(request.body?.timezone&&!deviceTimezone))return response.status(400).json({success:false,message:"A valid app, platform, device token, and IANA timezone are required."});const policy=await database.query(`SELECT * FROM goodbase_attestation_policies WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND app_id=$4 AND platform=$5 LIMIT 1`,[tenant.organizationId,tenant.projectId,tenant.environmentId,appId,platform]);let attestation=null;const attestationHeader=String(request.get("X-Goodbase-Attestation")||"");if(policy.rows[0]?.mode==="enforce"&&!attestationHeader)return response.status(401).json({success:false,code:"ATTESTATION_REQUIRED",message:"A valid app attestation token is required."});if(attestationHeader)attestation=await validateAttestationToken(attestationHeader,{appId});const providerType=platform==="ios"?"apns":platform==="android"||platform==="flutter"?"fcm":"web_push";const provider=await database.query(`SELECT * FROM goodbase_messaging_providers WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND provider_type=$4 AND status='ready' LIMIT 1`,[tenant.organizationId,tenant.projectId,tenant.environmentId,providerType]);if(!provider.rows[0])return response.status(503).json({success:false,code:"MESSAGING_PROVIDER_UNAVAILABLE",message:"Messaging is not configured for this platform."});const result=await database.query(`INSERT INTO goodbase_messaging_devices(organization_id,project_id,environment_id,app_id,user_id,provider_id,platform,token_hash,encrypted_token,locale,timezone,attestation_jti) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(app_id,token_hash) DO UPDATE SET user_id=EXCLUDED.user_id,provider_id=EXCLUDED.provider_id,encrypted_token=EXCLUDED.encrypted_token,locale=EXCLUDED.locale,timezone=EXCLUDED.timezone,attestation_jti=EXCLUDED.attestation_jti,status='active',last_seen_at=NOW(),updated_at=NOW() RETURNING id,status,platform,locale,timezone`,[tenant.organizationId,tenant.projectId,tenant.environmentId,appId,request.user.id,provider.rows[0].id,platform,sha256(rawToken),encryptValue(rawToken),clean(request.body?.locale,20)||null,deviceTimezone,attestation?.jti||null]);return response.status(201).json({success:true,device:result.rows[0]});
}catch(error){return next(error);}});

authenticatedRouter.delete("/messaging/devices/:id",async(request,response,next)=>{try{const result=await database.query(`UPDATE goodbase_messaging_devices SET status='revoked',encrypted_token='',updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING id`,[request.params.id,request.user.id]);if(!result.rows[0])return response.status(404).json({success:false,message:"Device not found."});return response.json({success:true,revoked:true});}catch(error){return next(error);}});

authenticatedRouter.use(dataPlaneAdminRequired);

authenticatedRouter.get("/assurance/overview",async(request,response,next)=>{try{const tenant=scope(request);const result=await database.query(`SELECT (SELECT status FROM goodbase_assurance_runs WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY created_at DESC LIMIT 1) AS latest_status,(SELECT COUNT(*)::int FROM goodbase_assurance_suites WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND enabled) AS enabled_suites,(SELECT COUNT(*)::int FROM goodbase_incident_exercises WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND status='passed') AS passed_incident_exercises`,[tenant.organizationId,tenant.projectId,tenant.environmentId]);return response.json({success:true,status:result.rows[0]});}catch(error){return next(error);}});
authenticatedRouter.post("/assurance/runs",mfaRequired,async(request,response,next)=>{try{const result=await runAssuranceSuite({suiteId:clean(request.body?.suiteId,100)||"assurance_daily_security",requestedBy:request.user.id,scope:scope(request)});return response.status(result.run.status==="passed"?201:503).json({success:result.run.status==="passed",...result});}catch(error){return next(error);}});

authenticatedRouter.get("/developer/assets",async(_request,response,next)=>{try{const result=await database.query(`SELECT * FROM goodbase_developer_assets WHERE status='published' ORDER BY asset_type,slug`);return response.json({success:true,assets:result.rows});}catch(error){return next(error);}});
authenticatedRouter.post("/imports/analyze",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const sourceType=clean(request.body?.sourceType,40);if(!["supabase","firebase_auth","firestore","firebase_storage","postgresql","environment"].includes(sourceType))return response.status(400).json({success:false,message:"Unsupported import source."});const fingerprint=sha256(JSON.stringify(request.body?.manifest||{}));const result=await database.query(`INSERT INTO goodbase_import_runs(organization_id,project_id,environment_id,source_type,status,dry_run,source_fingerprint,compatibility_json,requested_by) VALUES($1,$2,$3,$4,'validated',TRUE,$5,$6::jsonb,$7) RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,sourceType,fingerprint,JSON.stringify({analyzed:true,destructiveChanges:0,requiresApproval:true}),request.user.id]);return response.status(201).json({success:true,run:result.rows[0]});}catch(error){return next(error);}});
authenticatedRouter.post("/imports/:id/apply",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const rollbackRef=clean(request.body?.rollbackRef,500);if(!rollbackRef)return response.status(400).json({success:false,message:"A verified rollback reference is required."});const controller=await database.query(`SELECT * FROM goodbase_controller_registrations WHERE controller_type='infrastructure' AND status='ready' ORDER BY last_health_at DESC LIMIT 1`);if(!controller.rows[0])return response.status(503).json({success:false,code:"IMPORT_CONTROLLER_UNAVAILABLE",message:"A verified infrastructure controller is required before applying an import."});const run=await database.query(`UPDATE goodbase_import_runs SET status='ready',dry_run=FALSE,rollback_ref=$5 WHERE id=$4 AND organization_id=$1 AND project_id=$2 AND environment_id=$3 AND status='validated' RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,request.params.id,rollbackRef]);if(!run.rows[0])return response.status(404).json({success:false,message:"Validated import run not found."});const operation=await database.query(`INSERT INTO goodbase_controller_operations(controller_id,organization_id,project_id,environment_id,operation_type,idempotency_key,request_json,requested_by) VALUES($1,$2,$3,$4,'migration.import',$5,$6::jsonb,$7) RETURNING id,status`,[controller.rows[0].id,tenant.organizationId,tenant.projectId,tenant.environmentId,`import:${run.rows[0].id}`,JSON.stringify({importRunId:run.rows[0].id,sourceType:run.rows[0].source_type,sourceFingerprint:run.rows[0].source_fingerprint,rollbackRef}),request.user.id]);return response.status(202).json({success:true,operation:operation.rows[0],message:"Import queued with rollback protection; completion requires verified controller evidence."});}catch(error){return next(error);}});

authenticatedRouter.get("/attestation/policies",async(request,response,next)=>{try{const tenant=scope(request);const result=await database.query(`SELECT id,app_id,platform,provider,mode,token_ttl_seconds,provider_url,secret_ref,allowed_endpoints,configuration_json,updated_at FROM goodbase_attestation_policies WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY app_id,platform`,[tenant.organizationId,tenant.projectId,tenant.environmentId]);return response.json({success:true,policies:result.rows});}catch(error){return next(error);}});
authenticatedRouter.post("/attestation/policies",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const provider=clean(request.body?.provider,40);const platform=clean(request.body?.platform,20);const mode=clean(request.body?.mode,20);const providerUrl=clean(request.body?.providerUrl,500);const secretRef=clean(request.body?.secretRef,200);if(!["apple_app_attest","apple_devicecheck","play_integrity","recaptcha_enterprise","debug","custom"].includes(provider)||!["ios","android","web","flutter","custom"].includes(platform)||!["disabled","audit","enforce"].includes(mode))return response.status(400).json({success:false,message:"Invalid attestation policy."});if(provider==="debug"&&tenant.environmentId==="env_goodos_production")return response.status(400).json({success:false,code:"DEBUG_ATTESTATION_FORBIDDEN",message:"Debug attestation cannot be configured in production."});if(mode!=="disabled"&&provider==="debug"&&!secretRef)return response.status(400).json({success:false,message:"Debug attestation requires a secret reference."});if(mode!=="disabled"&&provider!=="debug"){let parsed;try{parsed=new URL(providerUrl);}catch{return response.status(400).json({success:false,message:"A valid HTTPS provider endpoint is required."});}if(parsed.protocol!=="https:"||!secretRef)return response.status(400).json({success:false,message:"Attestation requires an HTTPS provider endpoint and secret reference."});}const result=await database.query(`INSERT INTO goodbase_attestation_policies(organization_id,project_id,environment_id,app_id,platform,provider,mode,token_ttl_seconds,provider_url,secret_ref,allowed_endpoints,configuration_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ON CONFLICT(organization_id,project_id,environment_id,app_id,platform) DO UPDATE SET provider=EXCLUDED.provider,mode=EXCLUDED.mode,token_ttl_seconds=EXCLUDED.token_ttl_seconds,provider_url=EXCLUDED.provider_url,secret_ref=EXCLUDED.secret_ref,allowed_endpoints=EXCLUDED.allowed_endpoints,configuration_json=EXCLUDED.configuration_json,updated_at=NOW() RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,clean(request.body?.appId,100),platform,provider,mode,Math.min(Math.max(Number(request.body?.tokenTtlSeconds)||300,60),3600),providerUrl||null,secretRef||null,Array.isArray(request.body?.allowedEndpoints)?request.body.allowedEndpoints.slice(0,100):[],JSON.stringify(request.body?.configuration||{})]);return response.status(201).json({success:true,policy:result.rows[0]});}catch(error){return next(error);}});

authenticatedRouter.get("/messaging/providers",async(request,response,next)=>{try{const tenant=scope(request);const result=await database.query(`SELECT id,provider_type,status,endpoint_url,credential_ref,configuration_json,last_health_at,last_health_json FROM goodbase_messaging_providers WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY provider_type`,[tenant.organizationId,tenant.projectId,tenant.environmentId]);return response.json({success:true,providers:result.rows});}catch(error){return next(error);}});
authenticatedRouter.post("/messaging/providers",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const providerType=clean(request.body?.providerType,30);const endpointUrl=clean(request.body?.endpointUrl,500);const credentialRef=clean(request.body?.credentialRef,200);if(!["apns","fcm","web_push","custom"].includes(providerType))return response.status(400).json({success:false,message:"Unsupported messaging provider."});let parsed;try{parsed=new URL(endpointUrl);}catch{return response.status(400).json({success:false,message:"A valid HTTPS provider endpoint is required."});}if(parsed.protocol!=="https:")return response.status(400).json({success:false,message:"Messaging provider endpoints must use HTTPS."});const id=`messaging_${providerType}_${tenant.environmentId}`;const result=await database.query(`INSERT INTO goodbase_messaging_providers(id,organization_id,project_id,environment_id,provider_type,status,endpoint_url,credential_ref,configuration_json) VALUES($1,$2,$3,$4,$5,'misconfigured',$6,$7,$8::jsonb) ON CONFLICT(organization_id,project_id,environment_id,provider_type) DO UPDATE SET endpoint_url=EXCLUDED.endpoint_url,credential_ref=EXCLUDED.credential_ref,configuration_json=EXCLUDED.configuration_json,status='misconfigured',updated_at=NOW() RETURNING id,provider_type,status,endpoint_url,credential_ref,configuration_json`,[id,tenant.organizationId,tenant.projectId,tenant.environmentId,providerType,endpointUrl,credentialRef,JSON.stringify(request.body?.configuration||{})]);return response.status(201).json({success:true,provider:result.rows[0],message:"Provider saved as misconfigured until its signed health check succeeds."});}catch(error){return next(error);}});
authenticatedRouter.post("/messaging/providers/:id/verify",mfaRequired,async(request,response,next)=>{try{const result=await verifyMessagingProvider(request.params.id);return response.json({success:true,...result});}catch(error){return next(error);}});

authenticatedRouter.get("/auth/provider-configs",async(request,response,next)=>{try{const tenant=scope(request);const result=await database.query(`SELECT id,provider_type,display_name,status,issuer_url,client_id,secret_ref,controller_url,scopes,configuration_json,updated_at FROM goodbase_consumer_auth_providers WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY display_name`,[tenant.organizationId,tenant.projectId,tenant.environmentId]);return response.json({success:true,providers:result.rows});}catch(error){return next(error);}});
authenticatedRouter.patch("/auth/providers/:id",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const status=clean(request.body?.status,20);const controllerUrl=clean(request.body?.controllerUrl,500);const secretRef=clean(request.body?.secretRef,200);if(!["enabled","disabled","misconfigured"].includes(status))return response.status(400).json({success:false,message:"Invalid provider status."});const isAnonymous=request.params.id==='auth_consumer_anonymous';if(status==="enabled"&&!isAnonymous){let parsed;try{parsed=new URL(controllerUrl);}catch{return response.status(400).json({success:false,message:"A valid HTTPS controller URL is required."});}if(parsed.protocol!=="https:"||!secretRef)return response.status(400).json({success:false,message:"An HTTPS controller URL and secret reference are required before enabling this provider."});}const savedStatus=status==="enabled"&&!isAnonymous?"misconfigured":status;const result=await database.query(`UPDATE goodbase_consumer_auth_providers SET status=$5,issuer_url=$6,client_id=$7,secret_ref=$8,controller_url=$9,scopes=$10,configuration_json=$11::jsonb,updated_at=NOW() WHERE id=$4 AND organization_id=$1 AND project_id=$2 AND environment_id=$3 RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,request.params.id,savedStatus,clean(request.body?.issuerUrl,500)||null,clean(request.body?.clientId,300)||null,secretRef||null,controllerUrl||null,Array.isArray(request.body?.scopes)?request.body.scopes.slice(0,50):[],JSON.stringify(request.body?.configuration||{})]);if(!result.rows[0])return response.status(404).json({success:false,message:"Provider not found."});if(status==="enabled"&&!isAnonymous){await verifyConsumerAuthProvider(result.rows[0]);const enabled=await database.query(`UPDATE goodbase_consumer_auth_providers SET status='enabled',updated_at=NOW() WHERE id=$1 RETURNING *`,[result.rows[0].id]);return response.json({success:true,provider:enabled.rows[0],verified:true});}return response.json({success:true,provider:result.rows[0]});}catch(error){return next(error);}});

authenticatedRouter.post("/messaging/topics",async(request,response,next)=>{try{const tenant=scope(request);const name=clean(request.body?.name,120);if(!/^[a-z][a-z0-9_.-]{1,119}$/.test(name))return response.status(400).json({success:false,message:"Topic names must use lowercase letters, numbers, dots, underscores, or hyphens."});const result=await database.query(`INSERT INTO goodbase_messaging_topics(organization_id,project_id,environment_id,app_id,name,description) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,clean(request.body?.appId,100),name,clean(request.body?.description,500)||null]);return response.status(201).json({success:true,topic:result.rows[0]});}catch(error){if(error.code==="23505")error.statusCode=409;return next(error);}});
authenticatedRouter.post("/messaging/segments",async(request,response,next)=>{try{const tenant=scope(request);const rules=request.body?.rules||{};if((rules.platforms&&!Array.isArray(rules.platforms))||(rules.locales&&!Array.isArray(rules.locales)))return response.status(400).json({success:false,message:"Segment platform and locale filters must be arrays."});const result=await database.query(`INSERT INTO goodbase_messaging_segments(organization_id,project_id,environment_id,app_id,name,rule_json) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,clean(request.body?.appId,100),clean(request.body?.name,160),JSON.stringify({platforms:(rules.platforms||[]).slice(0,10),locales:(rules.locales||[]).slice(0,100)})]);return response.status(201).json({success:true,segment:result.rows[0]});}catch(error){if(error.code==="23505")error.statusCode=409;return next(error);}});
authenticatedRouter.post("/messaging/templates",async(request,response,next)=>{try{const tenant=scope(request);const key=clean(request.body?.templateKey,120);if(!/^[a-z][a-z0-9_.-]{1,119}$/.test(key))return response.status(400).json({success:false,message:"Invalid template key."});const result=await database.query(`INSERT INTO goodbase_messaging_templates(organization_id,project_id,environment_id,app_id,template_key,default_locale,content_json,localization_json,status) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,'draft') ON CONFLICT(app_id,template_key) DO UPDATE SET default_locale=EXCLUDED.default_locale,content_json=EXCLUDED.content_json,localization_json=EXCLUDED.localization_json,status='draft',updated_at=NOW() RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,clean(request.body?.appId,100),key,clean(request.body?.defaultLocale,20)||"en",JSON.stringify(request.body?.content||{}),JSON.stringify(request.body?.localizations||{})]);return response.status(201).json({success:true,template:result.rows[0]});}catch(error){return next(error);}});
authenticatedRouter.post("/messaging/campaigns",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const appId=clean(request.body?.appId,100);const name=clean(request.body?.name,160);const audienceType=clean(request.body?.audienceType,20);const content=request.body?.content||{};const scheduledAt=new Date(request.body?.scheduledAt||Date.now());if(!appId||!name||!["device","user","topic","segment","all"].includes(audienceType)||Number.isNaN(scheduledAt.getTime())||typeof content!=="object"||JSON.stringify(content).length>32768)return response.status(400).json({success:false,message:"A valid app, name, audience, schedule, and bounded content payload are required."});const result=await database.query(`INSERT INTO goodbase_messaging_campaigns(organization_id,project_id,environment_id,app_id,name,audience_type,audience_json,content_json,scheduled_at,timezone_mode,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,'scheduled',$11) RETURNING *`,[tenant.organizationId,tenant.projectId,tenant.environmentId,appId,name,audienceType,JSON.stringify(request.body?.audience||{}),JSON.stringify(content),scheduledAt.toISOString(),request.body?.timezoneMode==="device_local"?"device_local":"utc",request.user.id]);return response.status(201).json({success:true,campaign:result.rows[0]});}catch(error){return next(error);}});
authenticatedRouter.post("/messaging/campaigns/:id/queue",mfaRequired,async(request,response,next)=>{try{const tenant=scope(request);const campaign=await database.query(`UPDATE goodbase_messaging_campaigns SET status='scheduled',scheduled_at=NOW() WHERE id=$1 AND organization_id=$2 AND project_id=$3 AND environment_id=$4 AND status IN('scheduled','draft') RETURNING id,status,scheduled_at,audience_type`,[request.params.id,tenant.organizationId,tenant.projectId,tenant.environmentId]);if(!campaign.rows[0])return response.status(404).json({success:false,message:"Campaign not found or already dispatched."});return response.status(202).json({success:true,campaign:campaign.rows[0],message:"Campaign queued for audience-aware dispatch."});}catch(error){return next(error);}});

module.exports={publicRouter,authenticatedRouter};
