"use strict";
const crypto=require("crypto"),express=require("express"),rateLimit=require("express-rate-limit"),database=require("../config/database");
const router=express.Router();router.use(rateLimit({windowMs:60000,limit:120,standardHeaders:true,legacyHeaders:false}));
function safeEqual(left,right){const a=Buffer.from(String(left||"")),b=Buffer.from(String(right||""));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
router.post("/:operationId",async(request,response,next)=>{try{
  const timestamp=String(request.get("X-Goodbase-Timestamp")||""),signature=String(request.get("X-Goodbase-Signature")||"").replace(/^sha256=/,""),timestampNumber=Number(timestamp);
  if(!Number.isFinite(timestampNumber)||Math.abs(Date.now()-timestampNumber)>300000)return response.status(401).json({success:false,code:"GOODBASE_CONTROLLER_CALLBACK_EXPIRED",message:"Controller callback timestamp is invalid or expired."});
  const lookup=await database.query(`SELECT operation.*,controller.secret_ref FROM goodbase_controller_operations operation JOIN goodbase_controller_registrations controller ON controller.id=operation.controller_id WHERE operation.id=$1`,[request.params.operationId]);const operation=lookup.rows[0];
  if(!operation)return response.status(404).json({success:false,message:"Controller operation not found."});const secret=process.env[operation.secret_ref];if(!secret)return response.status(503).json({success:false,code:"GOODBASE_CONTROLLER_SECRET_MISSING",message:"Controller verification is unavailable."});
  const payload=JSON.stringify(request.body||{}),expected=crypto.createHmac("sha256",secret).update(`${timestamp}.${payload}`).digest("hex");if(!safeEqual(signature,expected))return response.status(401).json({success:false,code:"GOODBASE_CONTROLLER_CALLBACK_INVALID",message:"Controller callback signature is invalid."});
  if(!["succeeded","failed"].includes(request.body?.status))return response.status(400).json({success:false,message:"Callback status must be succeeded or failed."});
  const updated=await database.query(`UPDATE goodbase_controller_operations SET status=$2,result_json=$3::jsonb,rollback_evidence_json=$4::jsonb,failure_json=$5::jsonb,error_message=CASE WHEN $2='failed' THEN LEFT(COALESCE($6,'Controller operation failed.'),1000) ELSE NULL END,controller_request_id=COALESCE($7,controller_request_id),callback_received_at=NOW(),completed_at=NOW() WHERE id=$1 AND status IN('running','awaiting_callback',$2) RETURNING id,status,callback_received_at,completed_at`,[operation.id,request.body.status,JSON.stringify(request.body.result||{}),JSON.stringify(request.body.rollbackEvidence||{}),JSON.stringify(request.body.failure||{}),request.body.message||null,request.body.requestId||null]);
  if(!updated.rows[0])return response.status(409).json({success:false,message:"Controller operation is already finalized."});return response.json({success:true,operation:updated.rows[0]});
}catch(error){return next(error);}});module.exports=router;
