"use strict";

const crypto = require("crypto");
const database = require("../config/database");
const env = require("../config/env");
const { getSecretValue } = require("./secret.service");
const { observeBrowserPerformance } = require("../telemetry/metrics");
const symbolication = require("./goodbase-symbolication.service");

const DEFAULT_SCOPE = Object.freeze({ organizationId: "org_goodos", projectId: "proj_goodos_platform", environmentId: "env_goodos_production" });
const SENSITIVE_KEYS = /password|passcode|secret|token|authorization|cookie|session.?key|api.?key|credit.?card|cvv/i;

function clean(value, max = 200) { return String(value ?? "").trim().replace(/[\u0000-\u001f\u007f]/g, " ").slice(0, max); }
function sha256(value) { return crypto.createHash("sha256").update(String(value || "")).digest("hex"); }
function subjectHash({ userId, anonymousId, appId }) { return sha256(`${appId}:${userId || anonymousId || "unknown"}:${env.jwtSecret}`); }
function boundedJson(value, maxBytes = 65536) {
  const scrub = (input, depth = 0) => {
    if (depth > 6) return "[depth-limited]";
    if (Array.isArray(input)) return input.slice(0, 100).map((item) => scrub(item, depth + 1));
    if (!input || typeof input !== "object") return typeof input === "string" ? clean(input, 2000) : input;
    return Object.fromEntries(Object.entries(input).slice(0, 100).filter(([key]) => !SENSITIVE_KEYS.test(key)).map(([key, item]) => [clean(key, 100), scrub(item, depth + 1)]));
  };
  const safe = scrub(value || {}); const encoded = JSON.stringify(safe);
  if (Buffer.byteLength(encoded) > maxBytes) throw Object.assign(new Error("Payload metadata exceeds the allowed size."), { statusCode: 413, code: "GOODBASE_PAYLOAD_TOO_LARGE" });
  return safe;
}
function scopeParams(scope = DEFAULT_SCOPE) { return [scope.organizationId, scope.projectId, scope.environmentId]; }

async function ingestAnalytics({ scope = DEFAULT_SCOPE, userId = null, body, requestId = null }) {
  const appId = clean(body?.appId, 100); const anonymousId = clean(body?.anonymousId, 200) || null;
  const events = Array.isArray(body?.events) ? body.events : [];
  if (!appId || (!userId && !anonymousId) || events.length < 1 || events.length > 100) throw Object.assign(new Error("An app, subject, and 1–100 events are required."), { statusCode: 400 });
  const client = await database.pool.connect(); let accepted = 0; let denied = 0;
  try {
    await client.query("BEGIN");
    for (const event of events) {
      const consent = clean(event?.consentState || body?.consentState, 20);
      if (consent === "denied") { denied += 1; continue; }
      if (!["granted", "essential"].includes(consent)) throw Object.assign(new Error("Each event requires an explicit consent state."), { statusCode: 400 });
      const name = clean(event?.name, 120); const type = clean(event?.type || "custom", 30);
      if (!/^[A-Za-z][A-Za-z0-9_.:-]{0,119}$/.test(name) || !["custom","session","screen","conversion","revenue","campaign","exposure","server"].includes(type)) throw Object.assign(new Error("An event name or type is invalid."), { statusCode: 400 });
      const occurred = new Date(event?.occurredAt || Date.now()); if (Number.isNaN(occurred.getTime()) || occurred > new Date(Date.now() + 300000)) throw Object.assign(new Error("Event time is invalid."), { statusCode: 400 });
      const sessionId = clean(event?.sessionId || body?.sessionId, 200) || null; const hash = subjectHash({ userId, anonymousId, appId });
      await client.query(`INSERT INTO goodbase_analytics_events(organization_id,project_id,environment_id,app_id,user_id,subject_hash,anonymous_id,session_id,event_name,event_type,occurred_at,consent_state,properties_json,user_properties_json,attribution_json,revenue_amount,currency,source,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15::jsonb,$16,$17,$18,$19)`, [...scopeParams(scope),appId,userId,hash,anonymousId,sessionId,name,type,occurred.toISOString(),consent,JSON.stringify(boundedJson(event?.properties)),JSON.stringify(boundedJson(event?.userProperties,16384)),JSON.stringify(boundedJson(event?.attribution,16384)),event?.revenueAmount == null ? null : Math.max(0,Number(event.revenueAmount)||0),clean(event?.currency,3)||null,clean(event?.source||"client",30),requestId]);
      if (sessionId) await client.query(`INSERT INTO goodbase_analytics_sessions(id,organization_id,project_id,environment_id,app_id,user_id,anonymous_id,subject_hash,platform,country_code,language,app_version,started_at,ended_at,last_seen_at,event_count,consent_state,properties_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13,$13,1,$14,$15::jsonb) ON CONFLICT(id) DO UPDATE SET ended_at=GREATEST(goodbase_analytics_sessions.ended_at,EXCLUDED.ended_at),last_seen_at=GREATEST(goodbase_analytics_sessions.last_seen_at,EXCLUDED.last_seen_at),event_count=goodbase_analytics_sessions.event_count+1,consent_state=EXCLUDED.consent_state,subject_hash=COALESCE(goodbase_analytics_sessions.subject_hash,EXCLUDED.subject_hash)`, [sessionId,...scopeParams(scope),appId,userId,anonymousId,hash,clean(body?.platform,30)||null,clean(body?.countryCode,2)||null,clean(body?.language,20)||null,clean(body?.appVersion,60)||null,occurred.toISOString(),consent,JSON.stringify(boundedJson(body?.sessionProperties,8192))]);
      accepted += 1;
    }
    await client.query("COMMIT"); return { accepted, droppedForConsent: denied };
  } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
}

async function recordSession({scope=DEFAULT_SCOPE,userId=null,body}) {
  const appId=clean(body?.appId,100),sessionId=clean(body?.sessionId,200),anonymousId=clean(body?.anonymousId,200)||null,action=clean(body?.action||"heartbeat",20),consent=clean(body?.consentState,20);
  if(!appId||!sessionId||(!userId&&!anonymousId)||!["start","heartbeat","end"].includes(action))throw Object.assign(new Error("App, session, subject, and a valid lifecycle action are required."),{statusCode:400});
  if(consent==="denied")return{recorded:false,droppedForConsent:true};
  if(!["granted","essential"].includes(consent))throw Object.assign(new Error("Session lifecycle requires an explicit consent state."),{statusCode:400});
  const observed=new Date(body?.occurredAt||Date.now());if(Number.isNaN(observed.getTime())||observed>Date.now()+300000)throw Object.assign(new Error("Session time is invalid."),{statusCode:400});
  const releaseId=await symbolication.findRelease({scope,appId,releaseId:body?.releaseId,releaseName:body?.release,platform:body?.platform,buildNumber:body?.buildNumber});
  const endedReason=action==="end"&&["normal","background","timeout","crash"].includes(body?.endedReason)?body.endedReason:null;
  const installationHash=body?.installationId?subjectHash({appId,anonymousId:clean(body.installationId,300)}):null;
  const hash=subjectHash({userId,anonymousId,appId});
  const result=await database.query(`INSERT INTO goodbase_analytics_sessions(id,organization_id,project_id,environment_id,app_id,user_id,anonymous_id,subject_hash,platform,country_code,language,app_version,release_id,build_number,distribution_track,installation_hash,started_at,ended_at,last_seen_at,event_count,consent_state,properties_json,ended_reason,crashed,crash_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,CASE WHEN $18='end' THEN $17 END,$17,0,$19,$20::jsonb,$21,CASE WHEN $21='crash' THEN TRUE ELSE FALSE END,CASE WHEN $21='crash' THEN 1 ELSE 0 END) ON CONFLICT(id) DO UPDATE SET last_seen_at=GREATEST(goodbase_analytics_sessions.last_seen_at,EXCLUDED.last_seen_at),ended_at=CASE WHEN $18='end' THEN EXCLUDED.last_seen_at ELSE goodbase_analytics_sessions.ended_at END,ended_reason=COALESCE(EXCLUDED.ended_reason,goodbase_analytics_sessions.ended_reason),release_id=COALESCE(EXCLUDED.release_id,goodbase_analytics_sessions.release_id),app_version=COALESCE(EXCLUDED.app_version,goodbase_analytics_sessions.app_version),build_number=COALESCE(EXCLUDED.build_number,goodbase_analytics_sessions.build_number),distribution_track=COALESCE(EXCLUDED.distribution_track,goodbase_analytics_sessions.distribution_track),subject_hash=COALESCE(goodbase_analytics_sessions.subject_hash,EXCLUDED.subject_hash),consent_state=EXCLUDED.consent_state,properties_json=goodbase_analytics_sessions.properties_json||EXCLUDED.properties_json,crashed=goodbase_analytics_sessions.crashed OR EXCLUDED.crashed,crash_count=goodbase_analytics_sessions.crash_count+EXCLUDED.crash_count RETURNING id,app_id,release_id,started_at,ended_at,last_seen_at,crashed,crash_count,ended_reason`,[sessionId,...scopeParams(scope),appId,userId,anonymousId,hash,clean(body?.platform,30)||null,clean(body?.countryCode,2)||null,clean(body?.language,20)||null,clean(body?.appVersion||body?.release,60)||null,releaseId,clean(body?.buildNumber,100)||null,clean(body?.distributionTrack,100)||null,installationHash,observed.toISOString(),action,consent,JSON.stringify(boundedJson(body?.properties,8192)),endedReason]);
  return{recorded:true,session:result.rows[0]};
}

async function ingestCrash({ scope = DEFAULT_SCOPE, userId = null, body }) {
  const appId=clean(body?.appId,100), platform=clean(body?.platform,30), title=clean(body?.title||body?.exceptionType||"Unhandled error",300);
  if(!appId||!platform||!body?.occurredAt)throw Object.assign(new Error("App, platform, and occurrence time are required."),{statusCode:400});
  const rawStack=clean(body?.stackTrace,32000);
  const releaseId=await symbolication.findRelease({scope,appId,releaseId:body?.releaseId,releaseName:body?.release,platform,buildNumber:body?.buildNumber});
  const mapped=await symbolication.symbolicateStack({releaseId,stack:rawStack,platform});
  const stack=mapped.stack,normalizedStack=stack.replace(/0x[0-9a-f]+/gi,"0xADDR").replace(/:\d+(?::\d+)?/g,":LINE"),fingerprint=sha256(`${platform}:${clean(body?.exceptionType,200)}:${normalizedStack.split("\n").slice(0,8).join("\n")}`),variantKey=sha256(normalizedStack.split("\n").slice(0,24).join("\n")).slice(0,32),sessionId=clean(body?.sessionId,200)||null,anonymousId=clean(body?.anonymousId,200)||null;
  const client=await database.pool.connect();try{await client.query("BEGIN");
    const issue=await client.query(`INSERT INTO goodbase_crash_issues(organization_id,project_id,environment_id,app_id,fingerprint,platform,exception_type,title,first_release,last_release,occurrence_count,impacted_users,classification,last_classified_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,1,1,'new',NOW()) ON CONFLICT(app_id,fingerprint) DO UPDATE SET occurrence_count=goodbase_crash_issues.occurrence_count+1,last_release=EXCLUDED.last_release,last_seen_at=NOW(),status=CASE WHEN goodbase_crash_issues.status='resolved' THEN 'regressed' ELSE goodbase_crash_issues.status END,classification=CASE WHEN goodbase_crash_issues.status='resolved' THEN 'regressed' ELSE goodbase_crash_issues.classification END RETURNING *`,[...scopeParams(scope),appId,fingerprint,platform,clean(body?.exceptionType,200)||null,title,clean(body?.release,100)||null]);
    await client.query(`INSERT INTO goodbase_crash_occurrences(issue_id,release_id,user_id,anonymous_id,subject_hash,fatal,error_message,stack_trace,breadcrumbs_json,custom_keys_json,device_json,occurred_at,session_id,release_version,build_number,variant_key,symbolicated) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12,$13,$14,$15,$16,$17)`,[issue.rows[0].id,releaseId,userId,anonymousId,subjectHash({userId,anonymousId,appId}),body?.fatal!==false,clean(body?.message,4000)||null,stack||null,JSON.stringify(boundedJson(body?.breadcrumbs,32768)),JSON.stringify(boundedJson(body?.customKeys,16384)),JSON.stringify(boundedJson(body?.device,16384)),new Date(body.occurredAt).toISOString(),sessionId,clean(body?.release,100)||null,clean(body?.buildNumber,100)||null,variantKey,mapped.symbolicated]);
    await client.query(`INSERT INTO goodbase_crash_issue_variants(organization_id,project_id,environment_id,issue_id,variant_key,normalized_stack_hash,representative_stack,impacted_users) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(issue_id,variant_key) DO UPDATE SET occurrence_count=goodbase_crash_issue_variants.occurrence_count+1,last_seen_at=NOW(),impacted_users=goodbase_crash_issue_variants.impacted_users+EXCLUDED.impacted_users`,[...scopeParams(scope),issue.rows[0].id,variantKey,sha256(normalizedStack),stack||null,userId||anonymousId?1:0]);
    if(sessionId)await client.query(`UPDATE goodbase_analytics_sessions SET crashed=TRUE,crash_count=crash_count+1,ended_reason=CASE WHEN $2 THEN 'crash' ELSE ended_reason END,ended_at=CASE WHEN $2 THEN COALESCE(ended_at,$3) ELSE ended_at END,last_seen_at=GREATEST(last_seen_at,$3) WHERE id=$1`,[sessionId,body?.fatal!==false,new Date(body.occurredAt).toISOString()]);
    const impact=await client.query(`SELECT COUNT(DISTINCT COALESCE(user_id::text,anonymous_id))::bigint impacted_users,COUNT(DISTINCT session_id)::bigint impacted_sessions FROM goodbase_crash_occurrences WHERE issue_id=$1`,[issue.rows[0].id]);
    await client.query(`UPDATE goodbase_crash_issues SET impacted_users=$2,impacted_sessions=$3,impact_score=(occurrence_count*1.0)+($2*5.0)+($3*2.0) WHERE id=$1`,[issue.rows[0].id,impact.rows[0].impacted_users,impact.rows[0].impacted_sessions]);
    await client.query("COMMIT");return {issueId:issue.rows[0].id,fingerprint,status:issue.rows[0].status,classification:issue.rows[0].classification,variantKey,symbolicated:mapped.symbolicated,symbolicationTool:mapped.tool};
  }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}

async function ingestTrace({ scope=DEFAULT_SCOPE,userId=null,body }) {
  const appId=clean(body?.appId,100),type=clean(body?.type,30),name=clean(body?.name,200),duration=Number(body?.durationMs);
  if(!appId||!["startup","screen","network","custom","anr"].includes(type)||!name||!Number.isFinite(duration)||duration<0||duration>86400000)throw Object.assign(new Error("Trace payload is invalid."),{statusCode:400});
  const rate=Math.min(1,Math.max(0,Number(body?.sampleRate??0.1)));const sampleKey=sha256(`${appId}:${userId||body?.anonymousId||"unknown"}:${name}`);if(parseInt(sampleKey.slice(0,8),16)/0xffffffff>rate)return{sampled:false};
  const anonymousId=clean(body?.anonymousId,200)||null;
  const result=await database.query(`INSERT INTO goodbase_performance_traces(organization_id,project_id,environment_id,app_id,user_id,subject_hash,trace_type,name,duration_ms,success,platform,device_class,os_version,network_type,attributes_json,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16) RETURNING id`,[...scopeParams(scope),appId,userId,subjectHash({userId,anonymousId,appId}),type,name,duration,body?.success!==false,clean(body?.platform,30)||null,clean(body?.deviceClass,50)||null,clean(body?.osVersion,50)||null,clean(body?.networkType,30)||null,JSON.stringify(boundedJson(body?.attributes,16384)),new Date(body?.occurredAt||Date.now()).toISOString()]);
  observeBrowserPerformance({organizationId:scope.organizationId,appId,type,durationMs:duration,success:body?.success!==false});
  return{sampled:true,traceId:result.rows[0].id};
}

async function crashStability({scope=DEFAULT_SCOPE,appId,days=30}) {
  const boundedDays=Math.min(Math.max(Number(days)||30,1),365),params=[...scopeParams(scope),clean(appId,100)||null,boundedDays];
  const [summary,releases,issues]=await Promise.all([
    database.query(`WITH sessions AS (SELECT * FROM goodbase_analytics_sessions WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND ($4::text IS NULL OR app_id=$4) AND started_at>=NOW()-($5::text||' days')::interval), subjects AS (SELECT COALESCE(user_id::text,anonymous_id,installation_hash,id) subject,BOOL_OR(crashed) crashed FROM sessions GROUP BY 1) SELECT COUNT(*)::bigint total_sessions,COUNT(*) FILTER(WHERE crashed)::bigint crashed_sessions,ROUND(100.0*(COUNT(*)-COUNT(*) FILTER(WHERE crashed))/NULLIF(COUNT(*),0),4) crash_free_session_percent,(SELECT COUNT(*) FROM subjects)::bigint total_users,(SELECT COUNT(*) FROM subjects WHERE crashed)::bigint crashed_users,ROUND(100.0*((SELECT COUNT(*) FROM subjects)-(SELECT COUNT(*) FROM subjects WHERE crashed))/NULLIF((SELECT COUNT(*) FROM subjects),0),4) crash_free_user_percent FROM sessions`,params),
    database.query(`SELECT session.app_id,COALESCE(release.version,session.app_version,'unknown') version,COALESCE(release.build_number,session.build_number,'unknown') build_number,session.distribution_track,COUNT(*)::bigint sessions,COUNT(*) FILTER(WHERE session.crashed)::bigint crashed_sessions,ROUND(100.0*(COUNT(*)-COUNT(*) FILTER(WHERE session.crashed))/NULLIF(COUNT(*),0),4) crash_free_session_percent,ROUND(100.0*COUNT(*)/NULLIF(SUM(COUNT(*)) OVER(),0),4) adoption_percent FROM goodbase_analytics_sessions session LEFT JOIN goodbase_client_releases release ON release.id=session.release_id WHERE session.organization_id=$1 AND session.project_id=$2 AND session.environment_id=$3 AND ($4::text IS NULL OR session.app_id=$4) AND session.started_at>=NOW()-($5::text||' days')::interval GROUP BY 1,2,3,4 ORDER BY sessions DESC`,params),
    database.query(`SELECT issue.id,issue.app_id,issue.title,issue.platform,issue.status,issue.classification,issue.occurrence_count,issue.impacted_users,issue.impacted_sessions,issue.growth_percent,issue.impact_score,issue.first_seen_at,issue.last_seen_at,issue.last_release,(SELECT COUNT(*)::int FROM goodbase_crash_issue_variants variant WHERE variant.issue_id=issue.id) variants FROM goodbase_crash_issues issue WHERE issue.organization_id=$1 AND issue.project_id=$2 AND issue.environment_id=$3 AND ($4::text IS NULL OR issue.app_id=$4) ORDER BY issue.impact_score DESC,issue.last_seen_at DESC LIMIT 200`,params.slice(0,4))
  ]);
  return{windowDays:boundedDays,summary:summary.rows[0],releases:releases.rows,issues:issues.rows};
}

async function classifyCrashIssues() {
  const result=await database.query(`WITH windows AS (SELECT issue.id,COUNT(occurrence.id) FILTER(WHERE occurrence.occurred_at>=NOW()-INTERVAL '24 hours') current_count,COUNT(occurrence.id) FILTER(WHERE occurrence.occurred_at<NOW()-INTERVAL '24 hours' AND occurrence.occurred_at>=NOW()-INTERVAL '48 hours') previous_count FROM goodbase_crash_issues issue LEFT JOIN goodbase_crash_occurrences occurrence ON occurrence.issue_id=issue.id GROUP BY issue.id) UPDATE goodbase_crash_issues issue SET previous_window_occurrences=windows.previous_count,growth_percent=CASE WHEN windows.previous_count=0 THEN CASE WHEN windows.current_count>0 THEN 100 ELSE 0 END ELSE ROUND(100.0*(windows.current_count-windows.previous_count)/windows.previous_count,4) END,classification=CASE WHEN issue.status='regressed' THEN 'regressed' WHEN issue.first_seen_at>=NOW()-INTERVAL '24 hours' THEN 'new' WHEN windows.current_count>=5 AND windows.current_count>windows.previous_count*1.25 THEN 'growing' ELSE 'stable' END,impact_score=(windows.current_count*2.0)+(issue.impacted_users*5.0)+(issue.impacted_sessions*2.0),last_classified_at=NOW() FROM windows WHERE issue.id=windows.id RETURNING issue.id,issue.classification`);
  const alerts=await database.query(`WITH volumes AS (SELECT alert.id alert_id,alert.organization_id,alert.project_id,alert.environment_id,alert.app_id,alert.threshold,alert.window_minutes,COUNT(session.id)::bigint client_volume,COUNT(session.id) FILTER(WHERE session.crashed)::bigint crashed_volume FROM goodbase_telemetry_alerts alert LEFT JOIN goodbase_analytics_sessions session ON session.organization_id=alert.organization_id AND session.project_id=alert.project_id AND session.environment_id=alert.environment_id AND session.app_id=alert.app_id AND session.started_at>=NOW()-(alert.window_minutes::text||' minutes')::interval WHERE alert.status='active' AND alert.signal_type='crash_rate' GROUP BY alert.id), measured AS (SELECT *,CASE WHEN client_volume=0 THEN 0 ELSE 100.0*crashed_volume/client_volume END value FROM volumes) INSERT INTO goodbase_telemetry_alert_events(organization_id,project_id,environment_id,alert_id,app_id,measured_value,client_volume,threshold,window_started_at,window_ended_at,evidence_json) SELECT organization_id,project_id,environment_id,alert_id,app_id,value,client_volume,threshold,date_trunc('minute',NOW()-(window_minutes::text||' minutes')::interval),NOW(),jsonb_build_object('crashedSessions',crashed_volume,'minimumClientVolume',10) FROM measured WHERE client_volume>=10 AND value>=threshold ON CONFLICT(alert_id,window_started_at) DO UPDATE SET measured_value=EXCLUDED.measured_value,client_volume=EXCLUDED.client_volume,evidence_json=EXCLUDED.evidence_json RETURNING id`);
  return{classified:result.rowCount,volumeBackedAlerts:alerts.rowCount};
}

function matchesCondition(condition, context, subject) {
  if (!condition || typeof condition !== "object") return false;
  if (condition.percentage != null && parseInt(subject.slice(0,8),16)/0xffffffff*100 >= Number(condition.percentage)) return false;
  return ["country","language","platform","appVersion"].every((key)=>condition[key]==null||[].concat(condition[key]).map(String).includes(String(context[key]||"")));
}
function resolveParameters(parameters, conditions, context, subject) {
  const result={};for(const [key,definition] of Object.entries(parameters||{})){if(SENSITIVE_KEYS.test(key))continue;let value=definition?.default;for(const condition of conditions||[]){if(matchesCondition(condition,context,subject)&&condition.values&&Object.prototype.hasOwnProperty.call(condition.values,key))value=condition.values[key];}result[key]=value;}return result;
}
async function getRemoteConfig({appId,context={},subject="anonymous"}) {
  const found=await database.query(`SELECT template.id,template.published_version,version.id AS version_id,version.parameters_json,version.conditions_json,version.checksum_sha256 FROM goodbase_config_templates template JOIN goodbase_config_versions version ON version.template_id=template.id AND version.version_number=template.published_version WHERE template.app_id=$1 AND template.status='active' AND version.status='published' ORDER BY template.updated_at DESC LIMIT 1`,[appId]);const row=found.rows[0];if(!row)return{version:null,etag:null,parameters:{}};const hash=sha256(`${appId}:${subject}:${env.jwtSecret}`);return{version:row.published_version,etag:row.checksum_sha256,parameters:resolveParameters(row.parameters_json,row.conditions_json,context,hash)};
}

async function assignExperiments({appId,userId=null,anonymousId=null}) {const subject=subjectHash({appId,userId,anonymousId});const experiments=await database.query(`SELECT * FROM goodbase_experiments WHERE app_id=$1 AND status='running' ORDER BY created_at`,[appId]);const assignments=[];for(const experiment of experiments.rows){if(parseInt(sha256(`${subject}:${experiment.id}`).slice(0,8),16)/0xffffffff*100>Number(experiment.allocation_percent))continue;let existing=await database.query(`SELECT assignment.variant_id,variant.key,variant.payload_json FROM goodbase_experiment_assignments assignment JOIN goodbase_experiment_variants variant ON variant.id=assignment.variant_id WHERE assignment.experiment_id=$1 AND assignment.subject_hash=$2`,[experiment.id,subject]);if(!existing.rows[0]){const variants=await database.query(`SELECT * FROM goodbase_experiment_variants WHERE experiment_id=$1 ORDER BY key`,[experiment.id]);const total=variants.rows.reduce((sum,item)=>sum+Number(item.weight),0);let cursor=parseInt(sha256(`${experiment.id}:${subject}`).slice(0,8),16)/0xffffffff*total,selected=variants.rows[0];for(const variant of variants.rows){cursor-=Number(variant.weight);if(cursor<=0){selected=variant;break;}}if(!selected)continue;await database.query(`INSERT INTO goodbase_experiment_assignments(experiment_id,subject_hash,variant_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[experiment.id,subject,selected.id]);existing={rows:[{variant_id:selected.id,key:selected.key,payload_json:selected.payload_json}]};}assignments.push({experimentId:experiment.id,name:experiment.name,variantId:existing.rows[0].variant_id,variantKey:existing.rows[0].key,payload:existing.rows[0].payload_json});}return{subjectHash:subject,assignments};}

async function providerSecret(reference){if(!reference)return null;if(String(reference).startsWith("secret://"))return getSecretValue(reference);if(/^[A-Z][A-Z0-9_]{2,127}$/.test(String(reference)))return process.env[reference]||null;return null;}
async function signedProviderRequest(provider,body){const secret=await providerSecret(provider.secret_ref);if(!secret)throw Object.assign(new Error("Provider credential is unavailable."),{code:"PROVIDER_MISCONFIGURED"});const url=new URL(provider.endpoint_url);if(url.protocol!=="https:")throw new Error("Provider endpoint must use HTTPS.");const payload=JSON.stringify(body),timestamp=String(Date.now()),signature=crypto.createHmac("sha256",secret).update(`${timestamp}.${payload}`).digest("hex");const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),15000);try{const response=await fetch(url,{method:"POST",signal:abort.signal,headers:{"Content-Type":"application/json","X-Goodbase-Timestamp":timestamp,"X-Goodbase-Signature":`sha256=${signature}`,"Idempotency-Key":body.idempotencyKey},body:payload});const result=await response.json().catch(()=>({}));if(!response.ok||result.accepted!==true)throw new Error(result.message||`Provider returned ${response.status}.`);return result;}finally{clearTimeout(timeout);}}
async function verifyProvider(table,id){if(!["goodbase_distribution_providers","goodbase_cdn_providers"].includes(table))throw new Error("Invalid provider table.");const result=await database.query(`SELECT * FROM ${table} WHERE id=$1`,[id]),provider=result.rows[0];if(!provider)throw Object.assign(new Error("Provider not found."),{statusCode:404});try{const response=await signedProviderRequest(provider,{operation:"health",idempotencyKey:`health:${id}:${Date.now()}`});await database.query(`UPDATE ${table} SET status='ready',last_health_at=NOW(),updated_at=NOW() WHERE id=$1`,[id]);return{ready:true,response};}catch(error){await database.query(`UPDATE ${table} SET status='misconfigured',last_health_at=NOW(),updated_at=NOW() WHERE id=$1`,[id]);throw error;}}

async function dispatchProviderOperations(kind,limit=25){const distribution=kind==="distribution";const table=distribution?"goodbase_distribution_releases":"goodbase_cdn_operations";const providerTable=distribution?"goodbase_distribution_providers":"goodbase_cdn_providers";const rows=await database.query(`SELECT operation.*,provider.endpoint_url,provider.secret_ref,provider.status AS provider_status FROM ${table} operation JOIN ${providerTable} provider ON provider.id=operation.${distribution?"provider_id":"provider_id"} WHERE operation.status='queued' AND provider.status='ready' ORDER BY operation.created_at LIMIT $1 FOR UPDATE OF operation SKIP LOCKED`,[limit]);let completed=0,failed=0;for(const row of rows.rows){try{await database.query(`UPDATE ${table} SET status=$2 WHERE id=$1`,[row.id,distribution?"distributing":"running"]);const payload=distribution?{operation:"distribute",releaseId:row.id,buildId:row.build_id,groupId:row.group_id,idempotencyKey:row.idempotency_key}:{operation:row.operation_type,...row.request_json,idempotencyKey:row.idempotency_key};const response=await signedProviderRequest({endpoint_url:row.endpoint_url,secret_ref:row.secret_ref},payload);await database.query(`UPDATE ${table} SET status=$2,result_json=$3::jsonb,completed_at=NOW() WHERE id=$1`,[row.id,distribution?"available":"completed",JSON.stringify(boundedJson(response))]);completed++;}catch(error){await database.query(`UPDATE ${table} SET status='failed',${distribution?"result_json":"error_message"}=$2${distribution?"::jsonb":""},completed_at=NOW() WHERE id=$1`,[row.id,distribution?JSON.stringify({errorCode:error.code||"PROVIDER_FAILED"}):clean(error.code||error.message,300)]);failed++;}}return{processed:rows.rowCount,completed,failed};}

async function dispatchDistributionOperations(limit=25){const releases=await dispatchProviderOperations("distribution",limit);const tests=await database.query(`SELECT test.*,provider.endpoint_url,provider.secret_ref FROM goodbase_device_test_runs test JOIN goodbase_distribution_providers provider ON provider.id=test.provider_id WHERE test.status='queued' AND provider.status='ready' ORDER BY test.created_at LIMIT $1 FOR UPDATE OF test SKIP LOCKED`,[limit]);let completed=0,failed=0;for(const test of tests.rows){try{await database.query(`UPDATE goodbase_device_test_runs SET status='running',attempts=attempts+1 WHERE id=$1`,[test.id]);const response=await signedProviderRequest({endpoint_url:test.endpoint_url,secret_ref:test.secret_ref},{operation:"device_test",testRunId:test.id,buildId:test.build_id,testType:test.test_type,matrix:test.matrix_json,idempotencyKey:`device-test:${test.id}`});const status=["passed","failed","flaky"].includes(response.status)?response.status:"passed";await database.query(`UPDATE goodbase_device_test_runs SET status=$2,result_json=$3::jsonb,artifacts_json=$4::jsonb,completed_at=NOW() WHERE id=$1`,[test.id,status,JSON.stringify(boundedJson(response.result||response)),JSON.stringify(boundedJson(response.artifacts||[]))]);completed++;}catch(error){await database.query(`UPDATE goodbase_device_test_runs SET status=CASE WHEN attempts<3 THEN 'queued' ELSE 'failed' END,result_json=$2::jsonb,completed_at=CASE WHEN attempts<3 THEN NULL ELSE NOW() END WHERE id=$1`,[test.id,JSON.stringify({errorCode:error.code||"DEVICE_TEST_PROVIDER_FAILED"})]);failed++;}}return{releases,deviceTests:{processed:tests.rowCount,completed,failed}};}

async function rollupAnalytics(){const result=await database.query(`INSERT INTO goodbase_analytics_daily_metrics(organization_id,project_id,environment_id,app_id,metric_date,event_name,event_count,unique_users,revenue_amount) SELECT organization_id,project_id,environment_id,app_id,occurred_at::date,event_name,COUNT(*),COUNT(DISTINCT subject_hash),COALESCE(SUM(revenue_amount),0) FROM goodbase_analytics_events WHERE occurred_at>=CURRENT_DATE-INTERVAL '3 days' GROUP BY 1,2,3,4,5,6 ON CONFLICT(organization_id,project_id,environment_id,app_id,metric_date,event_name) DO UPDATE SET event_count=EXCLUDED.event_count,unique_users=EXCLUDED.unique_users,revenue_amount=EXCLUDED.revenue_amount,updated_at=NOW()`);return{metricsUpdated:result.rowCount};}
async function detectTelemetryRegressions(){const crashes=await database.query(`UPDATE goodbase_crash_issues SET status='regressed',classification='regressed',last_classified_at=NOW() WHERE status='resolved' AND last_seen_at>NOW()-INTERVAL '10 minutes' RETURNING id`);const intelligence=await classifyCrashIssues();return{crashRegressions:crashes.rowCount,...intelligence};}
async function evaluateExperiments(){const result=await database.query(`INSERT INTO goodbase_experiment_results(experiment_id,variant_id,metric_key,sample_size,conversion_rate,calculated_at) SELECT experiment.id,variant.id,experiment.primary_metric,COUNT(DISTINCT exposure.subject_hash),CASE WHEN COUNT(DISTINCT exposure.subject_hash)=0 THEN 0 ELSE COUNT(DISTINCT event.subject_hash)::numeric/COUNT(DISTINCT exposure.subject_hash) END,NOW() FROM goodbase_experiments experiment JOIN goodbase_experiment_variants variant ON variant.experiment_id=experiment.id LEFT JOIN goodbase_experiment_exposures exposure ON exposure.experiment_id=experiment.id AND exposure.variant_id=variant.id LEFT JOIN goodbase_analytics_events event ON event.app_id=experiment.app_id AND event.subject_hash=exposure.subject_hash AND event.event_name=experiment.primary_metric AND event.occurred_at>=exposure.occurred_at WHERE experiment.status='running' GROUP BY experiment.id,variant.id ON CONFLICT(experiment_id,variant_id,metric_key) DO UPDATE SET sample_size=EXCLUDED.sample_size,conversion_rate=EXCLUDED.conversion_rate,calculated_at=NOW()`);return{resultsUpdated:result.rowCount};}
async function reconcileCommercial(){const result=await database.query(`UPDATE goodbase_spend_limits limit_row SET status=CASE WHEN current_spend>=monthly_limit AND hard_stop THEN 'suspended' WHEN current_spend>=monthly_limit THEN 'exceeded' WHEN current_spend>=monthly_limit*warning_percent/100.0 THEN 'warning' ELSE 'active' END,updated_at=NOW() RETURNING id,status`);return{limitsReconciled:result.rowCount};}

module.exports={DEFAULT_SCOPE,clean,boundedJson,sha256,subjectHash,ingestAnalytics,recordSession,ingestCrash,ingestTrace,crashStability,classifyCrashIssues,getRemoteConfig,assignExperiments,verifyProvider,dispatchProviderOperations,dispatchDistributionOperations,rollupAnalytics,detectTelemetryRegressions,evaluateExperiments,reconcileCommercial};
