"use strict";

const crypto = require("crypto");
const database = require("../config/database");
const env = require("../config/env");
const { getSecretValue } = require("./secret.service");

const DEFAULT_SCOPE = Object.freeze({ organizationId: "org_goodos", projectId: "proj_goodos_platform", environmentId: "env_goodos_production" });
const SENSITIVE_KEYS = /password|passcode|secret|token|authorization|cookie|session.?key|api.?key|credit.?card|cvv/i;

function clean(value, max = 200) { return String(value ?? "").trim().replace(/[\u0000-\u001f\u007f]/g, " ").slice(0, max); }
function sha256(value) { return crypto.createHash("sha256").update(String(value || "")).digest("hex"); }
function subjectHash({ userId, anonymousId, appId }) { return sha256(`${appId}:${userId || anonymousId || "unknown"}:${env.jwtSecret}`); }
function boundedJson(value, maxBytes = 65536) {
  const scrub = (input, depth = 0) => {
    if (depth > 6) return "[depth-limited]";
    if (Array.isArray(input)) return input.slice(0, 100).map((item) => scrub(item, depth + 1));
    if (!input || typeof input !== "object") return typeof input === "string" ? clean(input, 2000) : input;
    return Object.fromEntries(Object.entries(input).slice(0, 100).filter(([key]) => !SENSITIVE_KEYS.test(key)).map(([key, item]) => [clean(key, 100), scrub(item, depth + 1)]));
  };
  const safe = scrub(value || {}); const encoded = JSON.stringify(safe);
  if (Buffer.byteLength(encoded) > maxBytes) throw Object.assign(new Error("Payload metadata exceeds the allowed size."), { statusCode: 413, code: "GOODBASE_PAYLOAD_TOO_LARGE" });
  return safe;
}
function scopeParams(scope = DEFAULT_SCOPE) { return [scope.organizationId, scope.projectId, scope.environmentId]; }

async function ingestAnalytics({ scope = DEFAULT_SCOPE, userId = null, body, requestId = null }) {
  const appId = clean(body?.appId, 100); const anonymousId = clean(body?.anonymousId, 200) || null;
  const events = Array.isArray(body?.events) ? body.events : [];
  if (!appId || (!userId && !anonymousId) || events.length < 1 || events.length > 100) throw Object.assign(new Error("An app, subject, and 1–100 events are required."), { statusCode: 400 });
  const client = await database.pool.connect(); let accepted = 0; let denied = 0;
  try {
    await client.query("BEGIN");
    for (const event of events) {
      const consent = clean(event?.consentState || body?.consentState, 20);
      if (consent === "denied") { denied += 1; continue; }
      if (!["granted", "essential"].includes(consent)) throw Object.assign(new Error("Each event requires an explicit consent state."), { statusCode: 400 });
      const name = clean(event?.name, 120); const type = clean(event?.type || "custom", 30);
      if (!/^[A-Za-z][A-Za-z0-9_.:-]{0,119}$/.test(name) || !["custom","session","screen","conversion","revenue","campaign","exposure","server"].includes(type)) throw Object.assign(new Error("An event name or type is invalid."), { statusCode: 400 });
      const occurred = new Date(event?.occurredAt || Date.now()); if (Number.isNaN(occurred.getTime()) || occurred > new Date(Date.now() + 300000)) throw Object.assign(new Error("Event time is invalid."), { statusCode: 400 });
      const sessionId = clean(event?.sessionId || body?.sessionId, 200) || null; const hash = subjectHash({ userId, anonymousId, appId });
      await client.query(`INSERT INTO goodbase_analytics_events(organization_id,project_id,environment_id,app_id,user_id,subject_hash,anonymous_id,session_id,event_name,event_type,occurred_at,consent_state,properties_json,user_properties_json,attribution_json,revenue_amount,currency,source,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15::jsonb,$16,$17,$18,$19)`, [...scopeParams(scope),appId,userId,hash,anonymousId,sessionId,name,type,occurred.toISOString(),consent,JSON.stringify(boundedJson(event?.properties)),JSON.stringify(boundedJson(event?.userProperties,16384)),JSON.stringify(boundedJson(event?.attribution,16384)),event?.revenueAmount == null ? null : Math.max(0,Number(event.revenueAmount)||0),clean(event?.currency,3)||null,clean(event?.source||"client",30),requestId]);
      if (sessionId) await client.query(`INSERT INTO goodbase_analytics_sessions(id,organization_id,project_id,environment_id,app_id,user_id,anonymous_id,platform,country_code,language,app_version,started_at,ended_at,event_count,consent_state,properties_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,1,$13,$14::jsonb) ON CONFLICT(id) DO UPDATE SET ended_at=GREATEST(goodbase_analytics_sessions.ended_at,EXCLUDED.ended_at),event_count=goodbase_analytics_sessions.event_count+1,consent_state=EXCLUDED.consent_state`, [sessionId,...scopeParams(scope),appId,userId,anonymousId,clean(body?.platform,30)||null,clean(body?.countryCode,2)||null,clean(body?.language,20)||null,clean(body?.appVersion,60)||null,occurred.toISOString(),consent,JSON.stringify(boundedJson(body?.sessionProperties,8192))]);
      accepted += 1;
    }
    await client.query("COMMIT"); return { accepted, droppedForConsent: denied };
  } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
}

async function ingestCrash({ scope = DEFAULT_SCOPE, userId = null, body }) {
  const appId=clean(body?.appId,100), platform=clean(body?.platform,30), title=clean(body?.title||body?.exceptionType||"Unhandled error",300);
  if(!appId||!platform||!body?.occurredAt)throw Object.assign(new Error("App, platform, and occurrence time are required."),{statusCode:400});
  const stack=clean(body?.stackTrace,32000), fingerprint=sha256(`${platform}:${clean(body?.exceptionType,200)}:${stack.split("\n").slice(0,8).join("\n")}`);
  const client=await database.pool.connect();try{await client.query("BEGIN");
    const issue=await client.query(`INSERT INTO goodbase_crash_issues(organization_id,project_id,environment_id,app_id,fingerprint,platform,exception_type,title,first_release,last_release,occurrence_count,impacted_users) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,1,$10) ON CONFLICT(app_id,fingerprint) DO UPDATE SET occurrence_count=goodbase_crash_issues.occurrence_count+1,last_release=EXCLUDED.last_release,last_seen_at=NOW(),status=CASE WHEN goodbase_crash_issues.status='resolved' THEN 'regressed' ELSE goodbase_crash_issues.status END,impacted_users=goodbase_crash_issues.impacted_users+CASE WHEN $10=1 THEN 1 ELSE 0 END RETURNING *`,[...scopeParams(scope),appId,fingerprint,platform,clean(body?.exceptionType,200)||null,title,clean(body?.release,100)||null,userId||body?.anonymousId?1:0]);
    await client.query(`INSERT INTO goodbase_crash_occurrences(issue_id,user_id,anonymous_id,fatal,error_message,stack_trace,breadcrumbs_json,custom_keys_json,device_json,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9::jsonb,$10)`,[issue.rows[0].id,userId,clean(body?.anonymousId,200)||null,body?.fatal!==false,clean(body?.message,4000)||null,stack||null,JSON.stringify(boundedJson(body?.breadcrumbs,32768)),JSON.stringify(boundedJson(body?.customKeys,16384)),JSON.stringify(boundedJson(body?.device,16384)),new Date(body.occurredAt).toISOString()]);
    await client.query("COMMIT");return {issueId:issue.rows[0].id,fingerprint,status:issue.rows[0].status};
  }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}

async function ingestTrace({ scope=DEFAULT_SCOPE,userId=null,body }) {
  const appId=clean(body?.appId,100),type=clean(body?.type,30),name=clean(body?.name,200),duration=Number(body?.durationMs);
  if(!appId||!["startup","screen","network","custom","anr"].includes(type)||!name||!Number.isFinite(duration)||duration<0||duration>86400000)throw Object.assign(new Error("Trace payload is invalid."),{statusCode:400});
  const rate=Math.min(1,Math.max(0,Number(body?.sampleRate??0.1)));const sampleKey=sha256(`${appId}:${userId||body?.anonymousId||"unknown"}:${name}`);if(parseInt(sampleKey.slice(0,8),16)/0xffffffff>rate)return{sampled:false};
  const result=await database.query(`INSERT INTO goodbase_performance_traces(organization_id,project_id,environment_id,app_id,user_id,trace_type,name,duration_ms,success,platform,device_class,os_version,network_type,attributes_json,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15) RETURNING id`,[...scopeParams(scope),appId,userId,type,name,duration,body?.success!==false,clean(body?.platform,30)||null,clean(body?.deviceClass,50)||null,clean(body?.osVersion,50)||null,clean(body?.networkType,30)||null,JSON.stringify(boundedJson(body?.attributes,16384)),new Date(body?.occurredAt||Date.now()).toISOString()]);return{sampled:true,traceId:result.rows[0].id};
}

function matchesCondition(condition, context, subject) {
  if (!condition || typeof condition !== "object") return false;
  if (condition.percentage != null && parseInt(subject.slice(0,8),16)/0xffffffff*100 >= Number(condition.percentage)) return false;
  return ["country","language","platform","appVersion"].every((key)=>condition[key]==null||[].concat(condition[key]).map(String).includes(String(context[key]||"")));
}
function resolveParameters(parameters, conditions, context, subject) {
  const result={};for(const [key,definition] of Object.entries(parameters||{})){if(SENSITIVE_KEYS.test(key))continue;let value=definition?.default;for(const condition of conditions||[]){if(matchesCondition(condition,context,subject)&&condition.values&&Object.prototype.hasOwnProperty.call(condition.values,key))value=condition.values[key];}result[key]=value;}return result;
}
async function getRemoteConfig({appId,context={},subject="anonymous"}) {
  const found=await database.query(`SELECT template.id,template.published_version,version.id AS version_id,version.parameters_json,version.conditions_json,version.checksum_sha256 FROM goodbase_config_templates template JOIN goodbase_config_versions version ON version.template_id=template.id AND version.version_number=template.published_version WHERE template.app_id=$1 AND template.status='active' AND version.status='published' ORDER BY template.updated_at DESC LIMIT 1`,[appId]);const row=found.rows[0];if(!row)return{version:null,etag:null,parameters:{}};const hash=sha256(`${appId}:${subject}:${env.jwtSecret}`);return{version:row.published_version,etag:row.checksum_sha256,parameters:resolveParameters(row.parameters_json,row.conditions_json,context,hash)};
}

async function assignExperiments({appId,userId=null,anonymousId=null}) {const subject=subjectHash({appId,userId,anonymousId});const experiments=await database.query(`SELECT * FROM goodbase_experiments WHERE app_id=$1 AND status='running' ORDER BY created_at`,[appId]);const assignments=[];for(const experiment of experiments.rows){if(parseInt(sha256(`${subject}:${experiment.id}`).slice(0,8),16)/0xffffffff*100>Number(experiment.allocation_percent))continue;let existing=await database.query(`SELECT assignment.variant_id,variant.key,variant.payload_json FROM goodbase_experiment_assignments assignment JOIN goodbase_experiment_variants variant ON variant.id=assignment.variant_id WHERE assignment.experiment_id=$1 AND assignment.subject_hash=$2`,[experiment.id,subject]);if(!existing.rows[0]){const variants=await database.query(`SELECT * FROM goodbase_experiment_variants WHERE experiment_id=$1 ORDER BY key`,[experiment.id]);const total=variants.rows.reduce((sum,item)=>sum+Number(item.weight),0);let cursor=parseInt(sha256(`${experiment.id}:${subject}`).slice(0,8),16)/0xffffffff*total,selected=variants.rows[0];for(const variant of variants.rows){cursor-=Number(variant.weight);if(cursor<=0){selected=variant;break;}}if(!selected)continue;await database.query(`INSERT INTO goodbase_experiment_assignments(experiment_id,subject_hash,variant_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[experiment.id,subject,selected.id]);existing={rows:[{variant_id:selected.id,key:selected.key,payload_json:selected.payload_json}]};}assignments.push({experimentId:experiment.id,name:experiment.name,variantId:existing.rows[0].variant_id,variantKey:existing.rows[0].key,payload:existing.rows[0].payload_json});}return{subjectHash:subject,assignments};}

async function providerSecret(reference){if(!reference)return null;if(String(reference).startsWith("secret://"))return getSecretValue(reference);if(/^[A-Z][A-Z0-9_]{2,127}$/.test(String(reference)))return process.env[reference]||null;return null;}
async function signedProviderRequest(provider,body){const secret=await providerSecret(provider.secret_ref);if(!secret)throw Object.assign(new Error("Provider credential is unavailable."),{code:"PROVIDER_MISCONFIGURED"});const url=new URL(provider.endpoint_url);if(url.protocol!=="https:")throw new Error("Provider endpoint must use HTTPS.");const payload=JSON.stringify(body),timestamp=String(Date.now()),signature=crypto.createHmac("sha256",secret).update(`${timestamp}.${payload}`).digest("hex");const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),15000);try{const response=await fetch(url,{method:"POST",signal:abort.signal,headers:{"Content-Type":"application/json","X-Goodbase-Timestamp":timestamp,"X-Goodbase-Signature":`sha256=${signature}`,"Idempotency-Key":body.idempotencyKey},body:payload});const result=await response.json().catch(()=>({}));if(!response.ok||result.accepted!==true)throw new Error(result.message||`Provider returned ${response.status}.`);return result;}finally{clearTimeout(timeout);}}
async function verifyProvider(table,id){if(!["goodbase_distribution_providers","goodbase_cdn_providers"].includes(table))throw new Error("Invalid provider table.");const result=await database.query(`SELECT * FROM ${table} WHERE id=$1`,[id]),provider=result.rows[0];if(!provider)throw Object.assign(new Error("Provider not found."),{statusCode:404});try{const response=await signedProviderRequest(provider,{operation:"health",idempotencyKey:`health:${id}:${Date.now()}`});await database.query(`UPDATE ${table} SET status='ready',last_health_at=NOW(),updated_at=NOW() WHERE id=$1`,[id]);return{ready:true,response};}catch(error){await database.query(`UPDATE ${table} SET status='misconfigured',last_health_at=NOW(),updated_at=NOW() WHERE id=$1`,[id]);throw error;}}

async function dispatchProviderOperations(kind,limit=25){const distribution=kind==="distribution";const table=distribution?"goodbase_distribution_releases":"goodbase_cdn_operations";const providerTable=distribution?"goodbase_distribution_providers":"goodbase_cdn_providers";const rows=await database.query(`SELECT operation.*,provider.endpoint_url,provider.secret_ref,provider.status AS provider_status FROM ${table} operation JOIN ${providerTable} provider ON provider.id=operation.${distribution?"provider_id":"provider_id"} WHERE operation.status='queued' AND provider.status='ready' ORDER BY operation.created_at LIMIT $1 FOR UPDATE OF operation SKIP LOCKED`,[limit]);let completed=0,failed=0;for(const row of rows.rows){try{await database.query(`UPDATE ${table} SET status=$2 WHERE id=$1`,[row.id,distribution?"distributing":"running"]);const payload=distribution?{operation:"distribute",releaseId:row.id,buildId:row.build_id,groupId:row.group_id,idempotencyKey:row.idempotency_key}:{operation:row.operation_type,...row.request_json,idempotencyKey:row.idempotency_key};const response=await signedProviderRequest({endpoint_url:row.endpoint_url,secret_ref:row.secret_ref},payload);await database.query(`UPDATE ${table} SET status=$2,result_json=$3::jsonb,completed_at=NOW() WHERE id=$1`,[row.id,distribution?"available":"completed",JSON.stringify(boundedJson(response))]);completed++;}catch(error){await database.query(`UPDATE ${table} SET status='failed',${distribution?"result_json":"error_message"}=$2${distribution?"::jsonb":""},completed_at=NOW() WHERE id=$1`,[row.id,distribution?JSON.stringify({errorCode:error.code||"PROVIDER_FAILED"}):clean(error.code||error.message,300)]);failed++;}}return{processed:rows.rowCount,completed,failed};}

async function dispatchDistributionOperations(limit=25){const releases=await dispatchProviderOperations("distribution",limit);const tests=await database.query(`SELECT test.*,provider.endpoint_url,provider.secret_ref FROM goodbase_device_test_runs test JOIN goodbase_distribution_providers provider ON provider.id=test.provider_id WHERE test.status='queued' AND provider.status='ready' ORDER BY test.created_at LIMIT $1 FOR UPDATE OF test SKIP LOCKED`,[limit]);let completed=0,failed=0;for(const test of tests.rows){try{await database.query(`UPDATE goodbase_device_test_runs SET status='running',attempts=attempts+1 WHERE id=$1`,[test.id]);const response=await signedProviderRequest({endpoint_url:test.endpoint_url,secret_ref:test.secret_ref},{operation:"device_test",testRunId:test.id,buildId:test.build_id,testType:test.test_type,matrix:test.matrix_json,idempotencyKey:`device-test:${test.id}`});const status=["passed","failed","flaky"].includes(response.status)?response.status:"passed";await database.query(`UPDATE goodbase_device_test_runs SET status=$2,result_json=$3::jsonb,artifacts_json=$4::jsonb,completed_at=NOW() WHERE id=$1`,[test.id,status,JSON.stringify(boundedJson(response.result||response)),JSON.stringify(boundedJson(response.artifacts||[]))]);completed++;}catch(error){await database.query(`UPDATE goodbase_device_test_runs SET status=CASE WHEN attempts<3 THEN 'queued' ELSE 'failed' END,result_json=$2::jsonb,completed_at=CASE WHEN attempts<3 THEN NULL ELSE NOW() END WHERE id=$1`,[test.id,JSON.stringify({errorCode:error.code||"DEVICE_TEST_PROVIDER_FAILED"})]);failed++;}}return{releases,deviceTests:{processed:tests.rowCount,completed,failed}};}

async function rollupAnalytics(){const result=await database.query(`INSERT INTO goodbase_analytics_daily_metrics(organization_id,project_id,environment_id,app_id,metric_date,event_name,event_count,unique_users,revenue_amount) SELECT organization_id,project_id,environment_id,app_id,occurred_at::date,event_name,COUNT(*),COUNT(DISTINCT subject_hash),COALESCE(SUM(revenue_amount),0) FROM goodbase_analytics_events WHERE occurred_at>=CURRENT_DATE-INTERVAL '3 days' GROUP BY 1,2,3,4,5,6 ON CONFLICT(organization_id,project_id,environment_id,app_id,metric_date,event_name) DO UPDATE SET event_count=EXCLUDED.event_count,unique_users=EXCLUDED.unique_users,revenue_amount=EXCLUDED.revenue_amount,updated_at=NOW()`);return{metricsUpdated:result.rowCount};}
async function detectTelemetryRegressions(){const crashes=await database.query(`UPDATE goodbase_crash_issues SET status='regressed' WHERE status='resolved' AND last_seen_at>NOW()-INTERVAL '10 minutes' RETURNING id`);return{crashRegressions:crashes.rowCount};}
async function evaluateExperiments(){const result=await database.query(`INSERT INTO goodbase_experiment_results(experiment_id,variant_id,metric_key,sample_size,conversion_rate,calculated_at) SELECT experiment.id,variant.id,experiment.primary_metric,COUNT(DISTINCT exposure.subject_hash),CASE WHEN COUNT(DISTINCT exposure.subject_hash)=0 THEN 0 ELSE COUNT(DISTINCT event.subject_hash)::numeric/COUNT(DISTINCT exposure.subject_hash) END,NOW() FROM goodbase_experiments experiment JOIN goodbase_experiment_variants variant ON variant.experiment_id=experiment.id LEFT JOIN goodbase_experiment_exposures exposure ON exposure.experiment_id=experiment.id AND exposure.variant_id=variant.id LEFT JOIN goodbase_analytics_events event ON event.app_id=experiment.app_id AND event.subject_hash=exposure.subject_hash AND event.event_name=experiment.primary_metric AND event.occurred_at>=exposure.occurred_at WHERE experiment.status='running' GROUP BY experiment.id,variant.id ON CONFLICT(experiment_id,variant_id,metric_key) DO UPDATE SET sample_size=EXCLUDED.sample_size,conversion_rate=EXCLUDED.conversion_rate,calculated_at=NOW()`);return{resultsUpdated:result.rowCount};}
async function reconcileCommercial(){const result=await database.query(`UPDATE goodbase_spend_limits limit_row SET status=CASE WHEN current_spend>=monthly_limit AND hard_stop THEN 'suspended' WHEN current_spend>=monthly_limit THEN 'exceeded' WHEN current_spend>=monthly_limit*warning_percent/100.0 THEN 'warning' ELSE 'active' END,updated_at=NOW() RETURNING id,status`);return{limitsReconciled:result.rowCount};}

module.exports={DEFAULT_SCOPE,clean,boundedJson,sha256,subjectHash,ingestAnalytics,ingestCrash,ingestTrace,getRemoteConfig,assignExperiments,verifyProvider,dispatchProviderOperations,dispatchDistributionOperations,rollupAnalytics,detectTelemetryRegressions,evaluateExperiments,reconcileCommercial};
