global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    platform: goodbase
    environment: production

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]
  - job_name: blackbox
    static_configs:
      - targets: ["blackbox:9115"]
  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: goodbase_https
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://base.goodos.app/api/enterprise/health
          - https://goodos.app/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: goodos_dns
    metrics_path: /probe
    params:
      module: [dns_goodos]
    static_configs:
      - targets: ["1.1.1.1:53"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
