"use strict";

const MAX_BREADCRUMBS=50,MAX_KEYS=64,STORAGE_PREFIX="goodbase.telemetry.v1";
function identifier(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function clean(value,max=2000){return String(value??"").replace(/[\u0000-\u001f\u007f]/g," ").slice(0,max);}
function safeObject(value,depth=0){if(depth>4)return"[depth-limited]";if(Array.isArray(value))return value.slice(0,50).map(item=>safeObject(item,depth+1));if(!value||typeof value!=="object")return typeof value==="string"?clean(value):value;return Object.fromEntries(Object.entries(value).slice(0,64).filter(([key])=>!/password|secret|token|authorization|cookie|api.?key/i.test(key)).map(([key,item])=>[clean(key,100),safeObject(item,depth+1)]));}

class GoodbaseTelemetry{
  constructor(options={}){if(!options.appId||!options.client||!options.release||!options.buildNumber)throw new Error("Goodbase telemetry requires appId, client, release, and buildNumber.");this.options=options;this.client=options.client;this.sessionId=identifier();this.consent=options.consent||"denied";this.breadcrumbs=[];this.customKeys={};this.started=false;this.handlers=[];this.bufferLimit=Math.min(Math.max(Number(options.bufferLimit)||100,10),1000);this.storageKey=`${STORAGE_PREFIX}.${options.appId}`;}
  base(){return{sessionId:this.sessionId,anonymousId:this.options.anonymousId,installationId:this.options.installationId,release:this.options.release,buildNumber:this.options.buildNumber,distributionTrack:this.options.distributionTrack,platform:"web",consentState:this.consent,occurredAt:new Date().toISOString()};}
  async start(){if(this.started||this.consent==="denied")return;this.started=true;await this.session("start");if(typeof addEventListener==="function"){this.listen(globalThis,"error",event=>this.captureException(event.error||event.message,{fatal:true,exceptionType:"window.error"}));this.listen(globalThis,"unhandledrejection",event=>this.captureException(event.reason,{fatal:true,exceptionType:"unhandledrejection"}));this.listen(globalThis,"online",()=>this.flush());this.listen(globalThis,"pagehide",()=>this.session("end","normal"));}if(typeof document!=="undefined")this.listen(document,"visibilitychange",()=>this.session(document.visibilityState==="hidden"?"end":"heartbeat",document.visibilityState==="hidden"?"background":undefined));this.observePerformance();await this.flush();}
  async stop(){if(!this.started)return;await this.session("end","normal");for(const [target,type,handler] of this.handlers)target.removeEventListener(type,handler);this.handlers=[];this.started=false;}
  listen(target,type,handler){target.addEventListener(type,handler);this.handlers.push([target,type,handler]);}
  async setConsent(consent){if(!["granted","essential","denied"].includes(consent))throw new Error("Invalid telemetry consent.");const previous=this.consent;this.consent=consent;if(consent==="denied"){this.clearBuffer();if(this.started)await this.stop();return;}if(previous==="denied")await this.start();}
  breadcrumb(message,data={}){this.breadcrumbs.push({message:clean(message,500),data:safeObject(data),at:new Date().toISOString()});if(this.breadcrumbs.length>MAX_BREADCRUMBS)this.breadcrumbs.shift();}
  setCustomKey(key,value){const name=clean(key,100);if(!name)return;if(!Object.prototype.hasOwnProperty.call(this.customKeys,name)&&Object.keys(this.customKeys).length>=MAX_KEYS)return;this.customKeys[name]=safeObject(value);}
  async session(action,endedReason){if(this.consent==="denied")return;await this.deliver("session",{...this.base(),action,endedReason,properties:{url:typeof location!=="undefined"?location.pathname:undefined,language:globalThis.navigator?.language}});}
  async captureException(error,options={}){if(this.consent==="denied")return;const value=error instanceof Error?error:new Error(clean(error));await this.deliver("crash",{...this.base(),title:clean(value.message||"Unhandled error",300),message:clean(value.message,4000),stackTrace:clean(value.stack,32000),exceptionType:clean(options.exceptionType||value.name,200),fatal:options.fatal===true,breadcrumbs:this.breadcrumbs.slice(),customKeys:{...this.customKeys},device:{userAgent:clean(globalThis.navigator?.userAgent,1000),language:globalThis.navigator?.language}});}
  async trace(name,operation,type="custom"){const start=globalThis.performance?.now?.()??Date.now();let success=true;try{return await operation();}catch(error){success=false;await this.captureException(error,{fatal:false,exceptionType:"nonfatal"});throw error;}finally{const end=globalThis.performance?.now?.()??Date.now();await this.deliver("trace",{...this.base(),type,name:clean(name,200),durationMs:end-start,success,sampleRate:1});}}
  observePerformance(){if(this.options.autoPerformance===false||typeof PerformanceObserver==="undefined")return;try{const observer=new PerformanceObserver(list=>{for(const entry of list.getEntries())this.deliver("trace",{...this.base(),type:entry.entryType==="navigation"?"startup":"custom",name:clean(entry.name||entry.entryType,200),durationMs:Math.max(0,entry.duration||0),success:true,sampleRate:1});});observer.observe({entryTypes:["navigation","largest-contentful-paint"]});this.performanceObserver=observer;}catch{}}
  readBuffer(){try{return JSON.parse(globalThis.localStorage?.getItem(this.storageKey)||"[]");}catch{return[];}}
  writeBuffer(items){try{globalThis.localStorage?.setItem(this.storageKey,JSON.stringify(items.slice(-this.bufferLimit)));}catch{}}
  clearBuffer(){try{globalThis.localStorage?.removeItem(this.storageKey);}catch{}}
  async deliver(kind,payload){try{if(globalThis.navigator?.onLine===false)throw new Error("offline");if(kind==="session")await this.client.recordSession(this.options.appId,payload);else if(kind==="crash")await this.client.captureCrash(this.options.appId,payload);else await this.client.recordTrace(this.options.appId,payload);}catch{const items=this.readBuffer();items.push({id:identifier(),kind,payload:safeObject(payload),queuedAt:new Date().toISOString()});this.writeBuffer(items);}}
  async flush(){if(this.consent==="denied"||globalThis.navigator?.onLine===false)return;const items=this.readBuffer(),remaining=[];for(const item of items){try{if(item.kind==="session")await this.client.recordSession(this.options.appId,item.payload);else if(item.kind==="crash")await this.client.captureCrash(this.options.appId,item.payload);else await this.client.recordTrace(this.options.appId,item.payload);}catch{remaining.push(item);}}this.writeBuffer(remaining);}
}
module.exports={GoodbaseTelemetry};
